// ========== CEX & DEX (40 tools) ==========
export const exchangeTools = [
  {
    id: "binance",
    name: "Binance",
    description: "World's largest crypto exchange by volume. 600+ coins, low fees, Binance Earn, and Web3 wallet.",
    category: "exchange",
    tags: ["Largest", "600+ Coins", "Low Fees"],
    url: "https://www.binance.com",
    affiliateUrl: "https://www.binance.com/en/register?ref=affiliate",
    pricing: "0.1% Maker/Taker",
    rating: 4.7,
    featured: true,
  },
  {
    id: "okx",
    name: "OKX",
    description: "Top-3 global crypto exchange. Advanced trading tools, Copy Trading, and Web3 ecosystem.",
    category: "exchange",
    tags: ["Top-3", "Advanced", "Web3"],
    url: "https://www.okx.com",
    affiliateUrl: "https://www.okx.com/affiliate",
    pricing: "0.1% Maker/Taker",
    rating: 4.6,
  },
  {
    id: "bybit",
    name: "Bybit",
    description: "Fast-growing crypto exchange with derivatives focus. Copy Trading and Launchpad.",
    category: "exchange",
    tags: ["Derivatives", "Copy Trading", "Launchpad"],
    url: "https://www.bybit.com",
    affiliateUrl: "https://www.bybit.com/en/register?affiliate",
    pricing: "0.1% Maker/Taker",
    rating: 4.5,
  },
  {
    id: "coinbase",
    name: "Coinbase",
    description: "US-regulated exchange. Most trusted by institutions. Advanced Trade and Base L2.",
    category: "exchange",
    tags: ["US Regulated", "Trusted", "Institutional"],
    url: "https://www.coinbase.com",
    affiliateUrl: "https://www.coinbase.com/join/affiliate",
    pricing: "0.4-0.6% (Advanced: 0.05-0.25%)",
    rating: 4.5,
  },
  {
    id: "kraken",
    name: "Kraken",
    description: "US-based exchange with strong security record. 220+ coins, staking, and futures.",
    category: "exchange",
    tags: ["Security", "220+ Coins", "Staking"],
    url: "https://www.kraken.com",
    affiliateUrl: "https://www.kraken.com/referral",
    pricing: "0-0.26% Maker/Taker",
    rating: 4.5,
  },
  {
    id: "kucoin",
    name: "KuCoin",
    description: "Altcoin-focused exchange with 700+ tokens. KuCoin Earn and Launchpad.",
    category: "exchange",
    tags: ["Altcoins", "700+ Tokens", "Earn"],
    url: "https://www.kucoin.com",
    pricing: "0.1% Maker/Taker",
    rating: 4.2,
  },
  {
    id: "bitget",
    name: "Bitget",
    description: "Derivatives-focused exchange with AI copy trading. 550+ coins and 500M+ users.",
    category: "exchange",
    tags: ["Derivatives", "AI Copy", "550+ Coins"],
    url: "https://www.bitget.com",
    affiliateUrl: "https://www.bitget.com/referral",
    pricing: "0.1% Maker/Taker",
    rating: 4.3,
  },
  {
    id: "huobi",
    name: "HTX (formerly Huobi)",
    description: "Established global exchange. 700+ trading pairs, HTX Earn, and Prime market.",
    category: "exchange",
    tags: ["Established", "700+ Pairs", "Earn"],
    url: "https://www.htx.com",
    pricing: "0.2% Maker/Taker",
    rating: 4.1,
  },
  {
    id: "gate",
    name: "Gate.io",
    description: "Comprehensive crypto exchange with 2,500+ tokens. Launchpad, margin, and futures.",
    category: "exchange",
    tags: ["2,500+ Tokens", "Launchpad", "Margin"],
    url: "https://www.gate.io",
    pricing: "0.2% Maker/Taker",
    rating: 4.2,
  },
  {
    id: "crypto-com",
    name: "Crypto.com",
    description: "Full crypto ecosystem: exchange, Visa card, DeFi, and NFT marketplace.",
    category: "exchange",
    tags: ["Visa Card", "DeFi", "NFT"],
    url: "https://crypto.com",
    pricing: "0.04-0.075% (CRO Discount)",
    rating: 4.3,
  },
  {
    id: "gemini",
    name: "Gemini",
    description: "NY-regulated exchange founded by Winklevoss twins. Institutional custody and Earn.",
    category: "exchange",
    tags: ["NY Regulated", "Institutional", "Earn"],
    url: "https://gemini.com",
    pricing: "0-0.4%",
    rating: 4.3,
  },
  {
    id: "mexc",
    name: "MEXC",
    description: "High-performance exchange with 2,000+ listings. MEXC Earn and Launchpad.",
    category: "exchange",
    tags: ["2,000+ Listings", "Earn", "Launchpad"],
    url: "https://www.mexc.com",
    pricing: "0.1% Maker/Taker",
    rating: 4.0,
  },
  {
    id: "bitfinex",
    name: "Bitfinex",
    description: "Veteran exchange with advanced trading features. High liquidity, margin, and lending.",
    category: "exchange",
    tags: ["Veteran", "High Liquidity", "Margin"],
    url: "https://www.bitfinex.com",
    pricing: "0-0.2% Maker/Taker",
    rating: 4.1,
  },
  {
    id: "bitstamp",
    name: "Bitstamp",
    description: "EU-licensed exchange since 2011. Trusted by institutional and retail traders.",
    category: "exchange",
    tags: ["EU Licensed", "Trusted", "Since 2011"],
    url: "https://bitstamp.net",
    pricing: "0.05-0.5%",
    rating: 4.2,
  },
  {
    id: "lbank",
    name: "LBank",
    description: "Global crypto exchange with 800+ tokens. Strong in Asian and emerging markets.",
    category: "exchange",
    tags: ["800+ Tokens", "Asian", "Emerging"],
    url: "https://www.lbank.com",
    pricing: "0.1% Maker/Taker",
    rating: 3.9,
  },
  {
    id: "upbit",
    name: "Upbit",
    description: "South Korea's largest crypto exchange. Strict listing requirements, 200+ coins.",
    category: "exchange",
    tags: ["Korea", "Largest", "200+ Coins"],
    url: "https://upbit.com",
    pricing: "0.05-0.25%",
    rating: 4.0,
  },
  {
    id: "bitso",
    name: "Bitso",
    description: "Latin America's largest crypto exchange. Mexico, Brazil, Argentina, Colombia.",
    category: "exchange",
    tags: ["Latin America", "Largest", "Fiat"],
    url: "https://bitso.com",
    pricing: "0.25-1%",
    rating: 3.8,
  },
  {
    id: "pionex-exchange",
    name: "Pionex Exchange",
    description: "Exchange with built-in free trading bots. 16 bots including Grid and DCA.",
    category: "exchange",
    tags: ["Free Bots", "16 Bots", "Built-in"],
    url: "https://pionex.com",
    pricing: "0.05% Maker/Taker",
    rating: 4.2,
  },
  {
    id: "bitrue",
    name: "Bitrue",
    description: "Exchange focused on XRP ecosystem. DeFi, staking, and lending features.",
    category: "exchange",
    tags: ["XRP", "DeFi", "Staking"],
    url: "https://www.bitrue.com",
    pricing: "0.1% Maker/Taker",
    rating: 3.8,
  },
  {
    id: "bingx",
    name: "BingX",
    description: "Social trading exchange with copy trading. 500+ coins and derivatives.",
    category: "exchange",
    tags: ["Social Trading", "Copy", "500+ Coins"],
    url: "https://bingx.com",
    pricing: "0.1% Maker/Taker",
    rating: 4.0,
  },
  {
    id: "phemex",
    name: "Phemex",
    description: "Fast derivatives exchange with 350+ contracts. Advanced order types.",
    category: "exchange",
    tags: ["Derivatives", "350+ Contracts", "Advanced Orders"],
    url: "https://phemex.com",
    pricing: "0.01-0.1%",
    rating: 4.0,
  },
  {
    id: "deribit",
    name: "Deribit",
    description: "Leading crypto options and futures exchange. 90%+ options market share.",
    category: "exchange",
    tags: ["Options", "Futures", "90% Options"],
    url: "https://www.deribit.com",
    pricing: "0.01-0.04%",
    rating: 4.5,
  },
  {
    id: "dmarket",
    name: "dYdX (Exchange)",
    description: "Decentralized perpetual futures exchange. Fully on-chain orderbook, zero gas trading.",
    category: "exchange",
    tags: ["DeFi", "Perpetuals", "On-Chain"],
    url: "https://dydx.exchange",
    pricing: "Protocol Fees",
    rating: 4.3,
  },
  {
    id: "gmx-exchange",
    name: "GMX (Exchange)",
    description: "Decentralized perpetuals on Arbitrum and Avalanche. Up to 50x leverage.",
    category: "exchange",
    tags: ["DeFi", "50x Leverage", "Arbitrum"],
    url: "https://gmx.io",
    pricing: "Protocol Fees",
    rating: 4.4,
  },
  {
    id: "raydium",
    name: "Raydium (DEX)",
    description: "Top Solana DEX with AMM and CLAMM. Concentrated liquidity and farming.",
    category: "exchange",
    tags: ["Solana", "CLAMM", "Farming"],
    url: "https://raydium.io",
    pricing: "Protocol Fees",
    rating: 4.2,
  },
  {
    id: "orca",
    name: "Orca (DEX)",
    description: "User-friendly Solana DEX with Whirlpools concentrated liquidity.",
    category: "exchange",
    tags: ["Solana", "Whirlpools", "User-Friendly"],
    url: "https://www.orca.so",
    pricing: "Protocol Fees",
    rating: 4.1,
  },
  {
    id: "jupiter",
    name: "Jupiter (DEX Aggregator)",
    description: "Leading Solana DEX aggregator. Best price routing across 100+ liquidity sources.",
    category: "exchange",
    tags: ["Solana", "Aggregator", "Best Price"],
    url: "https://jup.ag",
    pricing: "Protocol Fees",
    rating: 4.5,
  },
  {
    id: "spooky-swap",
    name: "SpookySwap (DEX)",
    description: "Leading DEX on Fantom. AMM with farms, bridges, and limit orders.",
    category: "exchange",
    tags: ["Fantom", "AMM", "Farms"],
    url: "https://spookyswap.finance",
    pricing: "Protocol Fees",
    rating: 4.0,
  },
  {
    id: "spirit-swap",
    name: "SpiritSwap (DEX)",
    description: "Fantom DEX with inSPIRIT veTokenomics and concentrated liquidity.",
    category: "exchange",
    tags: ["Fantom", "veToken", "CLAMM"],
    url: "https://spiritswap.finance",
    pricing: "Protocol Fees",
    rating: 3.9,
  },
  {
    id: "sushiswap",
    name: "SushiSwap (DEX)",
    description: "Multi-chain DEX. Trident AMM, Kashi lending, and MISO launchpad.",
    category: "exchange",
    tags: ["Multi-Chain", "AMM", "Launchpad"],
    url: "https://sushi.com",
    pricing: "Protocol Fees",
    rating: 4.1,
  },
  {
    id: "spiritswap",
    name: "BeamSwap (DEX)",
    description: "Top DEX on Moonbeam. AMM with farms and concentrated liquidity.",
    category: "exchange",
    tags: ["Moonbeam", "AMM", "Farms"],
    url: "https://beamswap.io",
    pricing: "Protocol Fees",
    rating: 3.8,
  },
  {
    id: "carbon-defi",
    name: "Carbon DeFi (DEX)",
    description: "Automated on-chain orders by Bancor. Limit orders with no deposits required.",
    category: "exchange",
    tags: ["Limit Orders", "Automated", "No Deposit"],
    url: "https://app.carbondefi.xyz",
    pricing: "Protocol Fees",
    rating: 3.9,
  },
  {
    id: "hashflow",
    name: "Hashflow (DEX)",
    description: "RFQ-based DEX aggregator. MEV protection and zero-slippage quotes.",
    category: "exchange",
    tags: ["RFQ", "MEV Protection", "Zero Slippage"],
    url: "https://hashflow.com",
    pricing: "Protocol Fees",
    rating: 4.1,
  },
  {
    id: "0x-api",
    name: "0x API (DEX Aggregator)",
    description: "DEX aggregator API powering Matcha and others. Best execution across DEXs.",
    category: "exchange",
    tags: ["API", "Aggregator", "Best Execution"],
    url: "https://0x.org",
    pricing: "Protocol Fees",
    rating: 4.3,
  },
  {
    id: "jupiter-limit",
    name: "Jupiter Limit Order (DEX)",
    description: "Decentralized limit order platform on Solana. Set price targets, automatic execution.",
    category: "exchange",
    tags: ["Solana", "Limit Order", "Automated"],
    url: "https://jup.ag/limit",
    pricing: "Protocol Fees",
    rating: 4.2,
  },
  {
    id: "kyber-swap",
    name: "KyberSwap (DEX Aggregator)",
    description: "Multi-chain DEX aggregator. Dynamic routing for best swap rates.",
    category: "exchange",
    tags: ["Multi-Chain", "Aggregator", "Dynamic Routing"],
    url: "https://kyberswap.com",
    pricing: "Protocol Fees",
    rating: 4.0,
  },
  {
    id: "1inch-v5",
    name: "1inch v5 (DEX Aggregator)",
    description: "Latest version of 1inch aggregator. Fusion mode for MEV protection.",
    category: "exchange",
    tags: ["Aggregator", "Fusion", "MEV Protection"],
    url: "https://1inch.io",
    pricing: "Protocol Fees",
    rating: 4.4,
  },
  {
    id: "woofi",
    name: "WOO X (Exchange)",
    description: "Professional trading platform by WOO Network. Zero-fee trading, deep liquidity.",
    category: "exchange",
    tags: ["Professional", "Zero-Fee", "Deep Liquidity"],
    url: "https://woo.org",
    pricing: "Zero Maker Fee",
    rating: 4.2,
  },
];
