// ========== SECURITY & AUDIT (50 tools) ==========
export const securityTools = [
  {
    id: "certik",
    name: "CertiK Skynet",
    description: "AI Auditor with 88.6% vulnerability detection rate. Multi-stage verification with real-time risk monitoring.",
    category: "security",
    tags: ["AI Audit", "Vulnerability", "Monitoring"],
    url: "https://certik.com",
    pricing: "Enterprise",
    rating: 4.5,
  },
  {
    id: "goplus",
    name: "GoPlus Security",
    description: "Most integrated Web3 security API. Built into CoinGecko, OKX, Trust Wallet. Honey pot and blacklist detection.",
    category: "security",
    tags: ["API", "Honey Pot", "Blacklist"],
    url: "https://gopluslabs.io",
    pricing: "Free / API Credits",
    rating: 4.4,
    featured: true,
  },
  {
    id: "token-sniffer",
    name: "Token Sniffer",
    description: "Token security scanner with 47.9M tokens indexed. 6.08M flagged as scams. 0-100 safety score.",
    category: "security",
    tags: ["Scanner", "Score", "Scam Detection"],
    url: "https://tokensniffer.com",
    pricing: "Free / Premium",
    rating: 4.3,
  },
  {
    id: "defi-scanner",
    name: "De.Fi Scanner",
    description: "Contract auditing with REKT database and DeFi security scoring. Comprehensive risk assessment.",
    category: "security",
    tags: ["Audit", "REKT DB", "Scoring"],
    url: "https://de.fi/scanner",
    pricing: "Free / Premium",
    rating: 4.2,
  },
  {
    id: "revoke-cash",
    name: "Revoke.cash",
    description: "Token approval auditing and malicious approval revocation. Essential wallet hygiene tool.",
    category: "security",
    tags: ["Approval", "Revoke", "Wallet"],
    url: "https://revoke.cash",
    pricing: "Free",
    rating: 4.6,
  },
  {
    id: "slowmist",
    name: "SlowMist",
    description: "Leading Chinese blockchain security firm. Smart contract audits and incident response.",
    category: "security",
    tags: ["Audit", "Incident Response", "Chinese"],
    url: "https://slowmist.io",
    pricing: "Enterprise",
    rating: 4.7,
  },
  {
    id: "consensys-diligence",
    name: "ConsenSys Diligence",
    description: "Smart contract security audits by ConsenSys. MythX automated analysis tool.",
    category: "security",
    tags: ["Audit", "MythX", "ConsenSys"],
    url: "https://consensys.io/diligence",
    pricing: "Enterprise",
    rating: 4.6,
  },
  {
    id: "trail-of-bits",
    name: "Trail of Bits",
    description: "Cybersecurity firm with deep crypto expertise. Smart contract audits and tools.",
    category: "security",
    tags: ["Audit", "Security Tools", "Deep Expertise"],
    url: "https://www.trailofbits.com",
    pricing: "Enterprise",
    rating: 4.5,
  },
  {
    id: "openzeppelin",
    name: "OpenZeppelin",
    description: "Security platform with Contracts library, Defender, and audit services. Industry standard.",
    category: "security",
    tags: ["Library", "Contracts", "Defender"],
    url: "https://openzeppelin.com",
    pricing: "Free / Enterprise",
    rating: 4.8,
  },
  {
    id: "quantstamp",
    name: "Quantstamp",
    description: "Smart contract security audits with 1M+ contracts secured. Automated and manual audits.",
    category: "security",
    tags: ["Audit", "Automated", "1M+ Secured"],
    url: "https://quantstamp.com",
    pricing: "Enterprise",
    rating: 4.4,
  },
  {
    id: "hacken",
    name: "Hacken",
    description: "Web3 security auditor with Proof of Reserves and penetration testing.",
    category: "security",
    tags: ["Audit", "Proof of Reserves", "Pen-Test"],
    url: "https://hacken.io",
    pricing: "Enterprise",
    rating: 4.3,
  },
  {
    id: "certora",
    name: "Certora",
    description: "Formal verification for smart contracts. Mathematical proof of correctness.",
    category: "security",
    tags: ["Formal Verification", "Mathematical", "Proof"],
    url: "https://certora.com",
    pricing: "Enterprise",
    rating: 4.5,
  },
  {
    id: "securify",
    name: "Securify",
    description: "Automated smart contract security scanner. Free online tool by ChainSecurity.",
    category: "security",
    tags: ["Automated", "Free", "ChainSecurity"],
    url: "https://securify.ch",
    pricing: "Free / Enterprise",
    rating: 4.0,
  },
  {
    id: "mythx",
    name: "MythX (ConsenSys)",
    description: "Smart contract security analysis platform. Detects vulnerabilities with multiple techniques.",
    category: "security",
    tags: ["Security Analysis", "Multiple Techniques", "ConsenSys"],
    url: "https://mythx.io",
    pricing: "$49-499/mo",
    rating: 4.3,
  },
  {
    id: "slither",
    name: "Slither (Trail of Bits)",
    description: "Static analysis framework for Solidity. Fast and accurate vulnerability detection.",
    category: "security",
    tags: ["Static Analysis", "Solidity", "Fast"],
    url: "https://github.com/crytic/slither",
    pricing: "Free (Open-Source)",
    rating: 4.6,
  },
  {
    id: "echidna",
    name: "Echidna (Trail of Bits)",
    description: "Property-based fuzzer for Ethereum smart contracts. Find edge cases.",
    category: "security",
    tags: ["Fuzzer", "Property-Based", "Edge Cases"],
    url: "https://github.com/crytic/echidna",
    pricing: "Free (Open-Source)",
    rating: 4.4,
  },
  {
    id: "manticore",
    name: "Manticore (Trail of Bits)",
    description: "Symbolic execution tool for smart contracts. Deep analysis of contract logic.",
    category: "security",
    tags: ["Symbolic Execution", "Deep Analysis", "Logic"],
    url: "https://github.com/trailofbits/manticore",
    pricing: "Free (Open-Source)",
    rating: 4.3,
  },
  {
    id: "smartcheck",
    name: "SmartCheck",
    description: "Online smart contract security checker. Quick vulnerability scan for Solidity.",
    category: "security",
    tags: ["Online", "Quick Scan", "Solidity"],
    url: "https://smartcheck.io",
    pricing: "Free",
    rating: 3.8,
  },
  {
    id: "deefi",
    name: "De.Fi (Security Suite)",
    description: "Full-stack DeFi security with audit, monitoring, and incident response.",
    category: "security",
    tags: ["Full-Stack", "Monitoring", "Incident"],
    url: "https://de.fi",
    pricing: "Free / Enterprise",
    rating: 4.1,
  },
  {
    id: "tenderly",
    name: "Tenderly",
    description: "Web3 development platform with smart contract monitoring and alerting.",
    category: "security",
    tags: ["Monitoring", "Alerting", "Development"],
    url: "https://tenderly.co",
    pricing: "Free / $49+/mo",
    rating: 4.5,
  },
  {
    id: "forta",
    name: "Forta",
    description: "Real-time detection network for smart contract threats. Decentralized security monitoring.",
    category: "security",
    tags: ["Real-time", "Detection", "Decentralized"],
    url: "https://forta.org",
    pricing: "Free / Token-based",
    rating: 4.3,
  },
  {
    id: "hexens",
    name: "Hexens",
    description: "Web3 security operations platform. Transaction simulation and risk scoring.",
    category: "security",
    tags: ["Security Ops", "Simulation", "Risk Score"],
    url: "https://hexens.io",
    pricing: "Enterprise",
    rating: 4.2,
  },
  {
    id: "hashi-corp",
    name: "HashiCorp (Crypto Ops)",
    description: "Infrastructure security for crypto companies. Vault for key management.",
    category: "security",
    tags: ["Infrastructure", "Vault", "Key Management"],
    url: "https://www.hashicorp.com",
    pricing: "Enterprise",
    rating: 4.4,
  },
  {
    id: "gnosis-safe",
    name: "Safe (Gnosis Safe)",
    description: "Most trusted multi-sig wallet. $100B+ secured across Web3.",
    category: "security",
    tags: ["Multi-Sig", "Trusted", "$100B+ Secured"],
    url: "https://safe.global",
    pricing: "Free",
    rating: 4.8,
  },
  {
    id: "firefly-wallet",
    name: "Firefly (Multisig)",
    description: "Multi-signature wallet for teams. Enhanced security for DAO and treasury.",
    category: "security",
    tags: ["Multi-Sig", "DAO", "Treasury"],
    url: "https://firefly.services",
    pricing: "Free / Premium",
    rating: 4.0,
  },
  {
    id: "wallet-guard",
    name: "Wallet Guard",
    description: "Browser extension protecting against wallet drainers and malicious approvals.",
    category: "security",
    tags: ["Browser", "Anti-Drainer", "Approval"],
    url: "https://walletguard.app",
    pricing: "Free",
    rating: 4.2,
  },
  {
    id: "blockaid",
    name: "Blockaid",
    description: "Web3 security API. Simulates transactions and detects threats before signing.",
    category: "security",
    tags: ["Simulation", "Threat Detection", "Pre-Sign"],
    url: "https://blockaid.io",
    pricing: "Enterprise",
    rating: 4.5,
  },
  {
    id: "pocket-universe",
    name: "Pocket Universe",
    description: "Transaction simulation browser extension. See what a transaction will do before signing.",
    category: "security",
    tags: ["Simulation", "Browser", "Pre-Sign"],
    url: "https://pocketuniverse.com",
    pricing: "Free",
    rating: 4.1,
  },
  {
    id: "ante-loans",
    name: "Ante Loans (Security Loans)",
    description: "Flash loan attack detection and prevention. Monitor for suspicious borrowing.",
    category: "security",
    tags: ["Flash Loan", "Detection", "Prevention"],
    url: "https://ante.finance",
    pricing: "Free / API",
    rating: 3.9,
  },
  {
    id: "solidity-finance",
    name: "Solidity Finance",
    description: "Smart contract audit firm with 500+ projects audited. Transparent reporting.",
    category: "security",
    tags: ["Audit", "500+ Projects", "Transparent"],
    url: "https://solidity.finance",
    pricing: "Enterprise",
    rating: 4.2,
  },
  {
    id: "coinspect",
    name: "CoinSpect",
    description: "Smart contract security audits with focus on DeFi protocols. Korean-based.",
    category: "security",
    tags: ["Audit", "DeFi", "Korean"],
    url: "https://coinspect.com",
    pricing: "Enterprise",
    rating: 4.1,
  },
  {
    id: "runtime-verification",
    name: "Runtime Verification",
    description: "Formal verification and smart contract auditing. KEVM and EVM formal semantics.",
    category: "security",
    tags: ["Formal Verification", "KEVM", "Semantics"],
    url: "https://runtimeverification.com",
    pricing: "Enterprise",
    rating: 4.3,
  },
  {
    id: "scythe",
    name: "Scythe",
    description: "Automated Web3 security testing. Fuzzing and property-based testing for smart contracts.",
    category: "security",
    tags: ["Automated", "Fuzzing", "Property-Based"],
    url: "https://scythe.io",
    pricing: "Enterprise",
    rating: 4.0,
  },
  {
    id: "immunebytes",
    name: "ImmuneBytes",
    description: "Smart contract audit platform with automated and manual review. Startup-friendly pricing.",
    category: "security",
    tags: ["Audit", "Startup-Friendly", "Automated+Manual"],
    url: "https://immunebytes.com",
    pricing: "$1,999-9,999",
    rating: 4.0,
  },
  {
    id: "palisade",
    name: "Palisade",
    description: "DeFi risk management platform. Monitor protocol risks and get early warnings.",
    category: "security",
    tags: ["Risk Management", "Monitoring", "Early Warning"],
    url: "https://palisade.io",
    pricing: "Free / Premium",
    rating: 3.9,
  },
  {
    id: "gauntlet",
    name: "Gauntlet",
    description: "DeFi risk management with agent-based simulation. Optimize protocol parameters.",
    category: "security",
    tags: ["Risk", "Simulation", "Optimization"],
    url: "https://gauntlet.network",
    pricing: "Enterprise",
    rating: 4.2,
  },
  {
    id: "chaos-labs",
    name: "Chaos Labs",
    description: "Protocol risk simulation and stress testing. Agent-based economic modeling.",
    category: "security",
    tags: ["Risk Simulation", "Stress Test", "Agent-Based"],
    url: "https://chaoslabs.xyz",
    pricing: "Enterprise",
    rating: 4.1,
  },
  {
    id: "boba-breach",
    name: "Boba Breach (Security Games)",
    description: "DeFi security competition platform. White-hat hackers compete to find bugs.",
    category: "security",
    tags: ["Competition", "White-Hat", "Bug Bounty"],
    url: "https://bobabreach.com",
    pricing: "Free / Bounties",
    rating: 3.8,
  },
  {
    id: "immunefi",
    name: "Immunefi",
    description: "Largest Web3 bug bounty platform. $150M+ in bounties paid to white-hats.",
    category: "security",
    tags: ["Bug Bounty", "$150M+ Paid", "White-Hat"],
    url: "https://immunefi.com",
    pricing: "Free / Platform Fee",
    rating: 4.6,
  },
  {
    id: "hackerone-crypto",
    name: "HackerOne (Crypto Programs)",
    description: "Bug bounty platform with many crypto/Web3 programs. Responsible disclosure.",
    category: "security",
    tags: ["Bug Bounty", "Responsible Disclosure", "Many Programs"],
    url: "https://www.hackerone.com",
    pricing: "Platform Fee",
    rating: 4.3,
  },
  {
    id: "code4rena",
    name: "Code4rena",
    description: "Competitive smart contract auditing. Wardens compete to find vulnerabilities.",
    category: "security",
    tags: ["Competitive", "Wardens", "Compete"],
    url: "https://code4rena.com",
    pricing: "Bounty-Based",
    rating: 4.5,
  },
  {
    id: "sherlock",
    name: "Sherlock",
    description: "Decentralized smart contract auditing protocol. Stake USDC to back audits.",
    category: "security",
    tags: ["Decentralized", "Stake", "USDC"],
    url: "https://www.sherlock.xyz",
    pricing: "Stake-Based",
    rating: 4.2,
  },
  {
    id: "yacademy",
    name: "YAcademy",
    description: "Smart contract audit education and competitive reviews. Train to be an auditor.",
    category: "security",
    tags: ["Education", "Competitive", "Train"],
    url: "https://www.yacademy.dev",
    pricing: "Free / Fellowship",
    rating: 4.0,
  },
  {
    id: "remix-ide",
    name: "Remix IDE",
    description: "Browser-based Solidity IDE with static analysis plugins. Quick contract testing.",
    category: "security",
    tags: ["IDE", "Browser-Based", "Static Analysis"],
    url: "https://remix.ethereum.org",
    pricing: "Free",
    rating: 4.3,
  },
  {
    id: "hardhat",
    name: "Hardhat",
    description: "Ethereum development environment with testing and debugging. Plugin ecosystem.",
    category: "security",
    tags: ["Development", "Testing", "Debugging"],
    url: "https://hardhat.org",
    pricing: "Free (Open-Source)",
    rating: 4.6,
  },
  {
    id: "foundry",
    name: "Foundry",
    description: "Blazing fast Ethereum development toolkit. Forge for testing, Cast for RPC.",
    category: "security",
    tags: ["Fast", "Testing", "Rust-Based"],
    url: "https://book.getfoundry.sh",
    pricing: "Free (Open-Source)",
    rating: 4.7,
  },
  {
    id: "anchor-solana",
    name: "Anchor (Solana)",
    description: "Solana smart contract framework with security best practices built-in.",
    category: "security",
    tags: ["Solana", "Framework", "Security Built-in"],
    url: "https://book.anchor-lang.com",
    pricing: "Free (Open-Source)",
    rating: 4.4,
  },
  {
    id: "eth-ssecurity-toolbox",
    name: "Ethereum Security Toolbox",
    description: "Collection of security tools for Ethereum developers. Not a single product but a curated list.",
    category: "security",
    tags: ["Collection", "Curated", "Developer"],
    url: "https://github.com/crytic/ethereum-security-toolbox",
    pricing: "Free",
    rating: 3.9,
  },
  {
    id: "decompile",
    name: "Decompile.ai",
    description: "AI-powered smart contract decompilation and analysis. Understand bytecode.",
    category: "security",
    tags: ["AI", "Decompile", "Bytecode"],
    url: "https://decompile.ai",
    pricing: "Free / Premium",
    rating: 3.8,
  },
  {
    id: "4byte",
    name: "4byte (Function Selector DB)",
    description: "Database of Ethereum function selectors. Lookup function signatures by hash.",
    category: "security",
    tags: ["Database", "Function Selector", "Lookup"],
    url: "https://www.4byte.directory",
    pricing: "Free",
    rating: 3.9,
  },
  // ========== SENTIMENT & NEWS (40 tools) ==========
  {
    id: "lunarcrush",
    name: "LunarCrush",
    description: "Social media aggregation with sentiment analysis across Twitter, Reddit, YouTube. AI-driven signals.",
    category: "sentiment",
    tags: ["Sentiment", "Social", "Signals"],
    url: "https://lunarcrush.com",
    affiliateUrl: "https://lunarcrush.com/affiliate-program",
    pricing: "Free / $49+/mo",
    rating: 4.3,
  },
  {
    id: "santiment",
    name: "Santiment",
    description: "On-chain and social sentiment tracking with developer activity and whale behavior monitoring.",
    category: "sentiment",
    tags: ["On-Chain", "Whales", "Development"],
    url: "https://santiment.net",
    pricing: "$49-449/mo",
    rating: 4.2,
  },
  {
    id: "kaito",
    name: "Kaito AI",
    description: "AI-powered crypto information aggregator with Mindshare ranking and AI search engine.",
    category: "sentiment",
    tags: ["AI Search", "Mindshare", "Aggregator"],
    url: "https://kaito.ai",
    pricing: "Free / Premium",
    rating: 4.4,
  },
  {
    id: "messari-sentiment",
    name: "Messari (Sentiment)",
    description: "Crypto research with AI-driven industry analysis and institutional-grade data.",
    category: "sentiment",
    tags: ["Research", "Institutional", "Data"],
    url: "https://messari.io",
    pricing: "$29-1000+/mo",
    rating: 4.5,
  },
  {
    id: "the-tie",
    name: "The TIE",
    description: "Crypto sentiment data and NLP analysis. Real-time sentiment scores for 7,000+ coins.",
    category: "sentiment",
    tags: ["NLP", "Real-time", "7,000+ Coins"],
    url: "https://www.thetie.io",
    pricing: "Enterprise",
    rating: 4.3,
  },
  {
    id: "augmento",
    name: "Augmento",
    description: "Sentiment analysis API with emotion detection. Track market emotions across social platforms.",
    category: "sentiment",
    tags: ["Emotion", "API", "Social"],
    url: "https://augmento.ai",
    pricing: "Free / API Credits",
    rating: 3.9,
  },
  {
    id: "stocktwits-crypto",
    name: "StockTwits (Crypto)",
    description: "Social sentiment platform for crypto. Real-time trader sentiment and message streams.",
    category: "sentiment",
    tags: ["Social", "Real-time", "Trader"],
    url: "https://stocktwits.com",
    pricing: "Free / Premium",
    rating: 4.0,
  },
  {
    id: "sentiment",
    name: "Sentiment Trader",
    description: "Traditional and crypto sentiment indicators. Contrarian sentiment signals.",
    category: "sentiment",
    tags: ["Contrarian", "Indicators", "Traditional+Crypto"],
    url: "https://sentimentrader.com",
    pricing: "$99-299/mo",
    rating: 4.1,
  },
  {
    id: "cryptoquant",
    name: "CryptoQuant",
    description: "On-chain and flow data with sentiment indicators. Exchange flows and miner positions.",
    category: "sentiment",
    tags: ["Flow Data", "Exchange", "Miner"],
    url: "https://cryptoquant.com",
    pricing: "$29-299/mo",
    rating: 4.4,
  },
  {
    id: "whalemap-sentiment",
    name: "WhaleMap (Sentiment)",
    description: "Bitcoin whale wallet tracking with sentiment overlay. Visual representation of holder behavior.",
    category: "sentiment",
    tags: ["Bitcoin", "Whales", "Visual"],
    url: "https://whalemap.com",
    pricing: "Free / $19/mo",
    rating: 4.1,
  },
  {
    id: "bitcoin-sentiment",
    name: "Bitcoin Sentiment Index",
    description: "Dedicated Bitcoin sentiment tracking. News and social media sentiment combined.",
    category: "sentiment",
    tags: ["Bitcoin", "News", "Social"],
    url: "https://bitcoinsentiment.io",
    pricing: "Free",
    rating: 3.8,
  },
  {
    id: "fear-greed",
    name: "Crypto Fear & Greed Index",
    description: "Daily sentiment index from 0-100. Tracks market emotions for contrarian signals.",
    category: "sentiment",
    tags: ["Index", "Fear", "Greed"],
    url: "https://alternative.me/crypto/fear-and-greed-index/",
    pricing: "Free",
    rating: 4.2,
  },
  {
    id: "tradingview-sentiment",
    name: "TradingView (Sentiment)",
    description: "Social sentiment from TradingView community. Most widely used sentiment overlay.",
    category: "sentiment",
    tags: ["Community", "Social", "Widely Used"],
    url: "https://tradingview.com/symbols/BTCUSD/sentiment/",
    pricing: "Free / $14.95-59.95/mo",
    rating: 4.5,
  },
  {
    id: "coingecko-sentiment",
    name: "CoinGecko (Sentiment)",
    description: "Community sentiment scores and social media buzz tracking. Most referenced sentiment data.",
    category: "sentiment",
    tags: ["Community", "Social", "Referenced"],
    url: "https://www.coingecko.com/en/coins/bitcoin",
    pricing: "Free / $32.5+/mo",
    rating: 4.4,
  },
  {
    id: "twitter-sentiment",
    name: "Twitter Crypto Sentiment (Custom)",
    description: "Custom Twitter sentiment analysis for crypto. Track specific coins or narratives.",
    category: "sentiment",
    tags: ["Twitter", "Custom", "Narrative"],
    url: "https://twitter.com/search",
    pricing: "Free / API",
    rating: 3.9,
  },
  {
    id: "reddit-crypto-sentiment",
    name: "Reddit Crypto Sentiment",
    description: "Reddit crypto community sentiment tracker. r/CryptoCurrency and niche subreddits.",
    category: "sentiment",
    tags: ["Reddit", "Community", "Niche"],
    url: "https://www.reddit.com/r/CryptoCurrency/",
    pricing: "Free",
    rating: 3.8,
  },
  {
    id: "newsbtc-sentiment",
    name: "NewsBTC Sentiment",
    description: "News-driven sentiment analysis. Track how news moves crypto prices.",
    category: "sentiment",
    tags: ["News", "Price Impact", "Analysis"],
    url: "https://www.newsbtc.com",
    pricing: "Free",
    rating: 3.9,
  },
  {
    id: "decrypt-sentiment",
    name: "Decrypt (News Sentiment)",
    description: "Crypto news with sentiment tracking. Quality journalism with sentiment context.",
    category: "sentiment",
    tags: ["News", "Journalism", "Context"],
    url: "https://decrypt.co",
    pricing: "Free / Premium",
    rating: 4.1,
  },
  {
    id: "coindesk-sentiment",
    name: "CoinDesk (News Sentiment)",
    description: "Leading crypto news with market sentiment analysis. Institutional-grade news.",
    category: "sentiment",
    tags: ["News", "Institutional", "Market"],
    url: "https://www.coindesk.com",
    pricing: "Free / $149+/yr",
    rating: 4.3,
  },
  {
    id: "cointelegraph-sentiment",
    name: "Cointelegraph (News Sentiment)",
    description: "Crypto news with sentiment indicators. Visual-heavy crypto journalism.",
    category: "sentiment",
    tags: ["News", "Visual", "Journalism"],
    url: "https://cointelegraph.com",
    pricing: "Free",
    rating: 4.2,
  },
  {
    id: "the-block-sentiment",
    name: "The Block (News Sentiment)",
    description: "Institutional crypto news with deep analysis. Subscription-based quality content.",
    category: "sentiment",
    tags: ["Institutional", "Deep Analysis", "Subscription"],
    url: "https://www.theblock.co",
    pricing: "$125-500+/yr",
    rating: 4.5,
  },
  {
    id: "ambcrypto-sentiment",
    name: "AMBCrypto (News Sentiment)",
    description: "Crypto news and sentiment tracking. Price prediction and market analysis.",
    category: "sentiment",
    tags: ["News", "Price Prediction", "Analysis"],
    url: "https://ambcrypto.com",
    pricing: "Free",
    rating: 3.8,
  },
  {
    id: "cryptonews-sentiment",
    name: "CryptoNews (Sentiment)",
    description: "Aggregated crypto news with sentiment analysis. Multi-source news aggregation.",
    category: "sentiment",
    tags: ["News", "Aggregated", "Multi-Source"],
    url: "https://cryptonews.com",
    pricing: "Free / Premium",
    rating: 3.9,
  },
  {
    id: "bitcoin-magazine-sentiment",
    name: "Bitcoin Magazine (Sentiment)",
    description: "Bitcoin-focused news and sentiment. OG Bitcoin publication since 2012.",
    category: "sentiment",
    tags: ["Bitcoin", "OG", "Since 2012"],
    url: "https://bitcoinmagazine.com",
    pricing: "Free / $99/yr",
    rating: 4.3,
  },
];
