// ========== WALLET & KEY (40 tools) ==========
export const walletTools = [
  {
    id: "metamask",
    name: "MetaMask",
    description: "Leading Ethereum wallet with 650K+ assets supported. AI transaction monitoring and smart gas prediction.",
    category: "wallet",
    tags: ["Ethereum", "dApp", "Gas"],
    url: "https://metamask.io",
    pricing: "Free",
    rating: 4.5,
  },
  {
    id: "trust-wallet",
    name: "Trust Wallet",
    description: "Open-source multi-chain wallet with NFT support. AI portfolio performance and smart trading suggestions.",
    category: "wallet",
    tags: ["Multi-Chain", "NFT", "Open Source"],
    url: "https://trustwallet.com",
    pricing: "Free",
    rating: 4.4,
  },
  {
    id: "zengo",
    name: "Zengo",
    description: "Seedless wallet with facial biometric security. AI fraud detection and transaction monitoring.",
    category: "wallet",
    tags: ["Seedless", "Biometric", "Security"],
    url: "https://zengo.com",
    pricing: "Free / Premium",
    rating: 4.3,
  },
  {
    id: "phantom",
    name: "Phantom",
    description: "Leading Solana wallet with in-app staking and NFT management. Sleek UI.",
    category: "wallet",
    tags: ["Solana", "Staking", "NFT"],
    url: "https://phantom.app",
    pricing: "Free",
    rating: 4.6,
  },
  {
    id: "solflare",
    name: "Solflare",
    description: "Web-based Solana wallet with staking and DeFi integration. Secure and simple.",
    category: "wallet",
    tags: ["Solana", "Staking", "Web-Based"],
    url: "https://solflare.com",
    pricing: "Free",
    rating: 4.3,
  },
  {
    id: "magic-eden-wallet",
    name: "Magic Eden Wallet",
    description: "Multi-chain NFT wallet by Magic Eden. Built for NFT collectors and traders.",
    category: "wallet",
    tags: ["NFT", "Multi-Chain", "Magic Eden"],
    url: "https://wallet.magiceden.io",
    pricing: "Free",
    rating: 4.1,
  },
  {
    id: "rainbow",
    name: "Rainbow",
    description: "Beautiful Ethereum wallet with DeFi integration. Best UI/UX in Web3.",
    category: "wallet",
    tags: ["Ethereum", "DeFi", "Beautiful UI"],
    url: "https://rainbow.me",
    pricing: "Free",
    rating: 4.5,
  },
  {
    id: "uniswap-wallet",
    name: "Uniswap Wallet",
    description: "Official Uniswap wallet with built-in swap and DeFi access. Open-source.",
    category: "wallet",
    tags: ["Uniswap", "DeFi", "Open-Source"],
    url: "https://wallet.uniswap.org",
    pricing: "Free",
    rating: 4.4,
  },
  {
    id: "coinbase-wallet",
    name: "Coinbase Wallet",
    description: "Self-custody wallet by Coinbase. Easy onboarding with dApp browser.",
    category: "wallet",
    tags: ["Self-Custody", "dApp", "Coinbase"],
    url: "https://www.coinbase.com/wallet",
    pricing: "Free",
    rating: 4.3,
  },
  {
    id: "okx-wallet",
    name: "OKX Wallet",
    description: "Multi-chain Web3 wallet by OKX. Swap, earn, and access 2000+ dApps.",
    category: "wallet",
    tags: ["Multi-Chain", "dApp", "OKX"],
    url: "https://www.okx.com/web3",
    pricing: "Free",
    rating: 4.4,
  },
  {
    id: "binance-web3-wallet",
    name: "Binance Web3 Wallet",
    description: "Binance's self-custody Web3 wallet. Integrated with Binance ecosystem.",
    category: "wallet",
    tags: ["Binance", "Web3", "Integrated"],
    url: "https://www.binance.com/en/web3wallet",
    pricing: "Free",
    rating: 4.2,
  },
  {
    id: "bybit-web3",
    name: "Bybit Web3 Wallet",
    description: "Web3 wallet by Bybit. Multi-chain with DeFi access and NFT support.",
    category: "wallet",
    tags: ["Bybit", "Multi-Chain", "DeFi"],
    url: "https://www.bybit.com/en/web3",
    pricing: "Free",
    rating: 4.1,
  },
  {
    id: "safe-wallet",
    name: "Safe Wallet (Gnosis Safe)",
    description: "Most trusted multi-sig wallet. $100B+ secured across Web3. Essential for teams.",
    category: "wallet",
    tags: ["Multi-Sig", "$100B+", "Teams"],
    url: "https://safe.global",
    pricing: "Free",
    rating: 4.8,
  },
  {
    id: "fire",
    name: "Fire",
    description: "Smart contract wallet with social recovery. No seed phrase, no gas fees (account abstraction).",
    category: "wallet",
    tags: ["Account Abstraction", "Social Recovery", "No Gas"],
    url: "https://www.fireblocks.com",
    pricing: "Enterprise",
    rating: 4.2,
  },
  {
    id: "argent",
    name: "Argent",
    description: "Smart contract wallet with social recovery and DeFi integration. No seed phrase needed.",
    category: "wallet",
    tags: ["Smart Contract", "Social Recovery", "DeFi"],
    url: "https://www.argent.xyz",
    pricing: "Free",
    rating: 4.3,
  },
  {
    id: "brave-wallet",
    name: "Brave Wallet",
    description: "Built-in crypto wallet in Brave browser. No extensions needed, privacy-focused.",
    category: "wallet",
    tags: ["Browser", "Privacy", "Built-in"],
    url: "https://brave.com/wallet/",
    pricing: "Free",
    rating: 4.0,
  },
  {
    id: "opera-crypto-browser",
    name: "Opera Crypto Browser",
    description: "Browser with built-in crypto wallet. Multi-chain support with seamless dApp access.",
    category: "wallet",
    tags: ["Browser", "Built-in", "Multi-Chain"],
    url: "https://www.opera.com/crypto",
    pricing: "Free",
    rating: 3.9,
  },
  {
    id: "exodus",
    name: "Exodus",
    description: "Beautiful multi-asset wallet with built-in exchange. 260+ assets supported, human support.",
    category: "wallet",
    tags: ["Multi-Asset", "Beautiful", "Human Support"],
    url: "https://www.exodus.com",
    pricing: "Free",
    rating: 4.5,
  },
  {
    id: "edge",
    name: "Edge Wallet",
    description: "Multi-currency wallet with client-side encryption. Private and secure, no account needed.",
    category: "wallet",
    tags: ["Multi-Currency", "Client-Side", "Private"],
    url: "https://edge.app",
    pricing: "Free",
    rating: 4.2,
  },
  {
    id: "atomic-wallet",
    name: "Atomic Wallet",
    description: "Multi-currency desktop and mobile wallet. Built-in exchange and staking.",
    category: "wallet",
    tags: ["Multi-Currency", "Desktop", "Staking"],
    url: "https://atomicwallet.io",
    pricing: "Free",
    rating: 4.1,
  },
  {
    id: "guarda",
    name: "Guarda Wallet",
    description: "Multi-currency wallet with Web, Desktop, Mobile, and Extension versions. 50+ blockchains.",
    category: "wallet",
    tags: ["Multi-Currency", "Multi-Platform", "50+ Chains"],
    url: "https://guarda.com",
    pricing: "Free",
    rating: 4.0,
  },
  {
    id: "myetherwallet",
    name: "MyEtherWallet (MEW)",
    description: "Original Ethereum wallet interface. Client-side, open-source, and nonprofit.",
    category: "wallet",
    tags: ["Ethereum", "Open-Source", "Client-Side"],
    url: "https://www.myetherwallet.com",
    pricing: "Free",
    rating: 4.3,
  },
  {
    id: "ledger-nano",
    name: "Ledger Nano (Hardware)",
    description: "Most popular hardware wallet. Secure offline storage with Ledger Live app.",
    category: "wallet",
    tags: ["Hardware", "Offline", "Secure"],
    url: "https://www.ledger.com",
    pricing: "$79-399 one-time",
    rating: 4.7,
  },
  {
    id: "trezor",
    name: "Trezor (Hardware)",
    description: "First hardware wallet. Open-source firmware with Trezor Suite app.",
    category: "wallet",
    tags: ["Hardware", "Open-Source", "First"],
    url: "https://trezor.io",
    pricing: "$69-219 one-time",
    rating: 4.6,
  },
  {
    id: "keepkey",
    name: "KeepKey (Hardware)",
    description: "Hardware wallet by ShapeShift. Large screen, open-source firmware.",
    category: "wallet",
    tags: ["Hardware", "Large Screen", "Open-Source"],
    url: "https://www.keepkey.com",
    pricing: "$49-129 one-time",
    rating: 4.0,
  },
  {
    id: "bitbox",
    name: "BitBox (Hardware)",
    description: "Minimalist hardware wallet from Shift Crypto. Open-source, compact design.",
    category: "wallet",
    tags: ["Hardware", "Minimalist", "Compact"],
    url: "https://shiftcrypto.ch",
    pricing: "$79-149 one-time",
    rating: 4.3,
  },
  {
    id: "coolwallet",
    name: "CoolWallet (Hardware)",
    description: "Credit-card sized hardware wallet. Bluetooth, mobile-first, bank-grade security.",
    category: "wallet",
    tags: ["Hardware", "Credit-Card", "Bluetooth"],
    url: "https://www.coolwallet.io",
    pricing: "$99-199 one-time",
    rating: 4.1,
  },
  {
    id: "ellipal",
    name: "Ellipal (Hardware)",
    description: "Air-gapped hardware wallet. QR code only, no USB/Bluetooth. Metal body.",
    category: "wallet",
    tags: ["Hardware", "Air-Gapped", "QR Only"],
    url: "https://www.ellipal.com",
    pricing: "$79-169 one-time",
    rating: 4.0,
  },
  {
    id: "keystone",
    name: "Keystone (Hardware)",
    description: "Open-source air-gapped hardware wallet. 4-inch touchscreen, QR code communication.",
    category: "wallet",
    tags: ["Hardware", "Open-Source", "Air-Gapped"],
    url: "https://keyst.one",
    pricing: "$119-199 one-time",
    rating: 4.3,
  },
  {
    id: "safeheron",
    name: "Safeheron (Institutional)",
    description: "Institutional-grade MPC wallet. No single point of failure, multi-party computation.",
    category: "wallet",
    tags: ["Institutional", "MPC", "Multi-Party"],
    url: "https://www.safeheron.com",
    pricing: "Enterprise",
    rating: 4.2,
  },
  {
    id: "fordefi",
    name: "Fordefi (Institutional)",
    description: "Institutional DeFi security platform. Policy engine with transaction simulation.",
    category: "wallet",
    tags: ["Institutional", "DeFi", "Policy Engine"],
    url: "https://fordefi.com",
    pricing: "Enterprise",
    rating: 4.1,
  },
  {
    id: "open-blockchain",
    name: "Open Blockchain (Wallet Tools)",
    description: "Open-source tools for blockchain key management. BIP32/39/44/84 libraries.",
    category: "wallet",
    tags: ["Open-Source", "Key Management", "BIP"],
    url: "https://github.com/OpenBlockchain",
    pricing: "Free",
    rating: 3.9,
  },
  {
    id: "iancoleman-tools",
    name: "Ian Coleman (BIP39 Tool)",
    description: "Offline BIP39 mnemonic code generator. Generate seeds and keys offline securely.",
    category: "wallet",
    tags: ["BIP39", "Offline", "Generator"],
    url: "https://iancoleman.io/bip39/",
    pricing: "Free",
    rating: 4.4,
  },
  {
    id: "walletconnect",
    name: "WalletConnect",
    description: "Open-source protocol for connecting wallets to dApps. Universal QR code standard.",
    category: "wallet",
    tags: ["Protocol", "Open-Source", "QR Code"],
    url: "https://walletconnect.com",
    pricing: "Free (Protocol)",
    rating: 4.5,
  },
  {
    id: "web3auth",
    name: "Web3Auth",
    description: "Pluggable auth infrastructure for Web3 wallets. Social login for Web3.",
    category: "wallet",
    tags: ["Auth", "Social Login", "Pluggable"],
    url: "https://web3auth.io",
    pricing: "Free / Enterprise",
    rating: 4.3,
  },
  {
    id: "dynamic",
    name: "Dynamic",
    description: "Smart wallet infrastructure with embedded wallets. Social login + self-custody.",
    category: "wallet",
    tags: ["Smart Wallet", "Embedded", "Social Login"],
    url: "https://www.dynamic.xyz",
    pricing: "Free / $99+/mo",
    rating: 4.2,
  },
  {
    id: "privy",
    name: "Privy",
    description: "Embedded wallets with social login. Seamless onboarding for Web3 apps.",
    category: "wallet",
    tags: ["Embedded", "Social Login", "Onboarding"],
    url: "https://www.privy.io",
    pricing: "Free / Enterprise",
    rating: 4.3,
  },
  // ========== NFT & GAMING (40 tools) ==========
  {
    id: "opensea",
    name: "OpenSea",
    description: "Largest NFT marketplace by volume. Buy, sell, and discover NFTs across multiple chains.",
    category: "nft",
    tags: ["Marketplace", "Multi-Chain", "Largest"],
    url: "https://opensea.io",
    pricing: "Platform Fees",
    rating: 4.5,
    featured: true,
  },
  {
    id: "blur",
    name: "Blur",
    description: "Professional NFT marketplace for traders. Pro tools, low fees, and BLUR rewards.",
    category: "nft",
    tags: ["Pro Tools", "Low Fees", "BLUR"],
    url: "https://blur.io",
    pricing: "Platform Fees",
    rating: 4.3,
  },
  {
    id: "magiceden",
    name: "Magic Eden",
    description: "Leading multi-chain NFT marketplace. Solana, Bitcoin, Ethereum, and Polygon NFTs.",
    category: "nft",
    tags: ["Multi-Chain", "Solana", "Bitcoin"],
    url: "https://magiceden.io",
    pricing: "Platform Fees",
    rating: 4.4,
  },
  {
    id: "looksrare",
    name: "LooksRare",
    description: "Community-first NFT marketplace. Lower fees, platform rewards for traders.",
    category: "nft",
    tags: ["Community", "Low Fees", "Rewards"],
    url: "https://looksrare.org",
    pricing: "Platform Fees",
    rating: 4.1,
  },
  {
    id: "x2y2",
    name: "X2Y2",
    description: "Decentralized NFT marketplace with P2P lending. Pro trading tools.",
    category: "nft",
    tags: ["Decentralized", "Lending", "Pro Tools"],
    url: "https://x2y2.io",
    pricing: "Platform Fees",
    rating: 3.9,
  },
  {
    id: "rarible",
    name: "Rarible",
    description: "Community-owned NFT marketplace. Multi-chain, create and trade NFTs with RARI rewards.",
    category: "nft",
    tags: ["Community-Owned", "Multi-Chain", "RARI"],
    url: "https://rarible.com",
    pricing: "Platform Fees",
    rating: 4.0,
  },
  {
    id: "superrare",
    name: "SuperRare",
    description: "Curated NFT marketplace for rare digital art. High-end art focus.",
    category: "nft",
    tags: ["Curated", "Art", "High-End"],
    url: "https://superrare.com",
    pricing: "Platform Fees",
    rating: 4.2,
  },
  {
    id: "foundation",
    name: "Foundation",
    description: "Creator-first NFT platform. Invite-only curation, focus on digital art.",
    category: "nft",
    tags: ["Creator-First", "Curated", "Art"],
    url: "https://foundation.app",
    pricing: "Platform Fees",
    rating: 4.0,
  },
  {
    id: "objkt",
    name: "Objkt (Tezos)",
    description: "Largest NFT marketplace on Tezos. Low fees, eco-friendly blockchain.",
    category: "nft",
    tags: ["Tezos", "Low Fees", "Eco-Friendly"],
    url: "https://objkt.com",
    pricing: "Platform Fees",
    rating: 3.8,
  },
  {
    id: "solesea",
    name: "SolSea (Solana)",
    description: "Solana NFT marketplace with programmable NFTs. Launchpad and secondary market.",
    category: "nft",
    tags: ["Solana", "Programmable", "Launchpad"],
    url: "https://solsea.io",
    pricing: "Platform Fees",
    rating: 3.9,
  },
  {
    id: "tensor",
    name: "Tensor (Solana)",
    description: "Professional Solana NFT trading platform. Real-time data, pro tools, TENSOR rewards.",
    category: "nft",
    tags: ["Solana", "Pro Tools", "TENSOR"],
    url: "https://www.tensor.trade",
    pricing: "Platform Fees",
    rating: 4.3,
  },
  {
    id: "uniswap-nft",
    name: "Uniswap NFT",
    description: "NFT aggregator by Uniswap. Sweep multiple NFTs across marketplaces in one transaction.",
    category: "nft",
    tags: ["Aggregator", "Sweep", "Uniswap"],
    url: "https://nft.uniswap.org",
    pricing: "Platform Fees",
    rating: 4.1,
  },
  {
    id: "gem-xyz",
    name: "Gem (OpenSea)",
    description: "NFT aggregator acquired by OpenSea. Multi-collection sweep with low fees.",
    category: "nft",
    tags: ["Aggregator", "Sweep", "OpenSea"],
    url: "https://www.gem.xyz",
    pricing: "Platform Fees",
    rating: 4.0,
  },
  {
    id: "reservoir-nft",
    name: "Reservoir (NFT API)",
    description: "NFT marketplace aggregation API. Unified access to NFT liquidity across all major marketplaces.",
    category: "nft",
    tags: ["API", "Aggregation", "Unified"],
    url: "https://reservoir.tools",
    pricing: "Free / Enterprise",
    rating: 4.2,
  },
  {
    id: "alchemy-nft-api",
    name: "Alchemy NFT API",
    description: "Comprehensive NFT data API. Fetch metadata, ownership, and sales history across chains.",
    category: "nft",
    tags: ["API", "Multi-Chain", "Metadata"],
    url: "https://www.alchemy.com/nft-api",
    pricing: "Free / $199+/mo",
    rating: 4.4,
  },
  {
    id: "moralis-nft",
    name: "Moralis NFT API",
    description: "NFT data API with real-time updates. Fetch NFTs by wallet, collection, or contract.",
    category: "nft",
    tags: ["API", "Real-time", "Multi-Chain"],
    url: "https://moralis.io/nft-api",
    pricing: "Free / $49+/mo",
    rating: 4.3,
  },
  {
    id: "nftexpress",
    name: "NFT Express",
    description: "Real-time NFT analytics and tracking. Whale wallets, mint tracking, and rarity tools.",
    category: "nft",
    tags: ["Analytics", "Whale Tracking", "Mint"],
    url: "https://nftexpress.com",
    pricing: "Free / $29+/mo",
    rating: 4.1,
  },
  {
    id: "rarity-sniper",
    name: "Rarity Sniper",
    description: "NFT rarity tools and real-time mint tracking. Sniper bot for new mints.",
    category: "nft",
    tags: ["Rarity", "Mint Tracking", "Bot"],
    url: "https://raritysnipe.com",
    pricing: "Free / $9.99/mo",
    rating: 4.0,
  },
  {
    id: "nftgo",
    name: "NFTGo",
    description: "NFT analytics platform with whale tracking and real-time mint calendar.",
    category: "nft",
    tags: ["Analytics", "Whale", "Mint Calendar"],
    url: "https://nftgo.io",
    pricing: "Free / Premium",
    rating: 4.2,
  },
  {
    id: "icy-tools",
    name: "Icy Tools",
    description: "Real-time NFT analytics. Track mints, sales, and whale activity as they happen.",
    category: "nft",
    tags: ["Real-time", "Analytics", "Whale"],
    url: "https://icy.tools",
    pricing: "$30-150/mo",
    rating: 4.3,
  },
  {
    id: "nansen-nft",
    name: "Nansen NFT",
    description: "NFT analytics with Smart Money integration. Track profitable NFT wallets.",
    category: "nft",
    tags: ["Smart Money", "Analytics", "Profitable"],
    url: "https://nansen.ai/nft",
    pricing: "Included in Nansen Plans",
    rating: 4.4,
  },
  {
    id: "dappradar-nft",
    name: "DappRadar (NFT)",
    description: "NFT market overview and analytics. Track sales volume, traders, and collections.",
    category: "nft",
    tags: ["Market Overview", "Analytics", "Collections"],
    url: "https://dappradar.com/nft",
    pricing: "Free / Pro",
    rating: 4.3,
  },
  {
    id: "opensea-pro",
    name: "OpenSea Pro (Gem)",
    description: "Professional NFT trading terminal. Advanced order types, real-time data, and low fees.",
    category: "nft",
    tags: ["Pro Terminal", "Advanced", "Low Fees"],
    url: "https://pro.opensea.io",
    pricing: "Platform Fees",
    rating: 4.2,
  },
  {
    id: "nftniq",
    name: "NFTNiq",
    description: "Compressed NFT tracking on Solana. Real-time data for cNFT collections.",
    category: "nft",
    tags: ["Solana", "Compressed", "Real-time"],
    url: "https://nftniq.com",
    pricing: "Free / Premium",
    rating: 3.9,
  },
  {
    id: "birthdaysniper",
    name: "Birthday Sniper",
    description: "Automated NFT mint sniper. Execute mints at exactly the right moment.",
    category: "nft",
    tags: ["Mint", "Sniper", "Automated"],
    url: "https://birthdaysniper.com",
    pricing: "From 0.1 SOL/mint",
    rating: 3.8,
  },
  {
    id: "monkelab",
    name: "MonkeLab (Solana Tools)",
    description: "Solana NFT tools. Rarity, floor price tracking, and whale alerts.",
    category: "nft",
    tags: ["Solana", "Rarity", "Whale Alerts"],
    url: "https://monkelab.com",
    pricing: "Free / Premium",
    rating: 3.9,
  },
  {
    id: "howrareyou",
    name: "HowRareAreYou (Solana)",
    description: "Solana NFT rarity and analytics. Track your portfolio and discover new collections.",
    category: "nft",
    tags: ["Solana", "Rarity", "Portfolio"],
    url: "https://howrare.is",
    pricing: "Free / Premium",
    rating: 4.0,
  },
  {
    id: "solanafloor",
    name: "SolanaFloor",
    description: "Solana NFT floor price tracker. Real-time floor prices across all major collections.",
    category: "nft",
    tags: ["Solana", "Floor Price", "Real-time"],
    url: "https://solanafloor.com",
    pricing: "Free / Premium",
    rating: 4.1,
  },
  {
    id: "stepn",
    name: "STEPN",
    description: "Move-to-earn NFT game on Solana. Buy sneakers NFTs and earn GST by walking.",
    category: "nft",
    tags: ["GameFi", "Move-to-Earn", "Solana"],
    url: "https://stepn.com",
    pricing: "Free / NFT Purchase",
    rating: 4.0,
  },
  {
    id: "axie-infinity",
    name: "Axie Infinity",
    description: "Pioneering P2E game on Ronin. Collect, breed, and battle Axies.",
    category: "nft",
    tags: ["P2E", "Ronin", "Pioneering"],
    url: "https://axieinfinity.com",
    pricing: "Free / NFT Purchase",
    rating: 3.9,
  },
  {
    id: "the-sandbox",
    name: "The Sandbox",
    description: "Voxel-based metaverse game. Buy LAND NFTs and create voxel assets.",
    category: "nft",
    tags: ["Metaverse", "Voxel", "LAND"],
    url: "https://www.sandbox.game",
    pricing: "Free / LAND Purchase",
    rating: 4.1,
  },
  {
    id: "decentraland",
    name: "Decentraland",
    description: "Browser-based metaverse. Buy LAND NFTs, create scenes, and earn MANA.",
    category: "nft",
    tags: ["Metaverse", "Browser-Based", "LAND"],
    url: "https://decentraland.org",
    pricing: "Free / LAND Purchase",
    rating: 4.0,
  },
  {
    id: "gala-games",
    name: "Gala Games",
    description: "Web3 gaming ecosystem with multiple P2E titles. Node ecosystem and GALA token.",
    category: "nft",
    tags: ["Gaming", "P2E", "Node"],
    url: "https://galagames.com",
    pricing: "Free / Game Purchase",
    rating: 4.0,
  },
  {
    id: "immutable-x",
    name: "Immutable X",
    description: "Layer 2 for NFTs and gaming on Ethereum. Gas-free minting and trading.",
    category: "nft",
    tags: ["L2", "Gas-Free", "Gaming"],
    url: "https://www.immutable.com",
    pricing: "Platform Fees",
    rating: 4.3,
  },
  {
    id: "polygon-nft",
    name: "Polygon NFT",
    description: "Low-cost NFT ecosystem on Polygon. Mint and trade with near-zero fees.",
    category: "nft",
    tags: ["Low-Cost", "Near-Zero Fees", "Ethereum L2"],
    url: "https://polygon.technology/nft",
    pricing: "Platform Fees",
    rating: 4.1,
  },
  {
    id: "tezos-nft",
    name: "Tezos NFT (Objkt/Hen)",
    description: "Eco-friendly NFT ecosystem on Tezos. Low fees, artist-friendly platform.",
    category: "nft",
    tags: ["Eco-Friendly", "Low Fees", "Artist-Friendly"],
    url: "https://objkt.com",
    pricing: "Platform Fees",
    rating: 3.8,
  },
  {
    id: "cardano-nft",
    name: "Cardano NFT (JPG Store)",
    description: "Cardano NFT marketplace. CNFT ecosystem with low fees and native assets.",
    category: "nft",
    tags: ["Cardano", "Low Fees", "Native Assets"],
    url: "https://www.jpg.store",
    pricing: "Platform Fees",
    rating: 3.9,
  },
];
