export interface Tool {
  id: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  url: string;
  affiliateUrl?: string;
  pricing: string;
  rating: number;
  featured?: boolean;
}

export const categories = [
  { id: "all", name: "All Tools", count: 50 },
  { id: "trading-bots", name: "Trading Bots", count: 12 },
  { id: "analytics", name: "On-Chain Analytics", count: 8 },
  { id: "portfolio", name: "Portfolio Management", count: 6 },
  { id: "defi", name: "DeFi AI", count: 8 },
  { id: "security", name: "Security & Audit", count: 5 },
  { id: "sentiment", name: "Sentiment & News", count: 4 },
  { id: "charting", name: "Chart & TA", count: 4 },
  { id: "wallet", name: "Wallet & Key", count: 3 },
];

export const tools: Tool[] = [
  // Trading Bots
  {
    id: "3commas",
    name: "3Commas",
    description: "All-in-one trading platform with smart terminals and AI bots. Supports DCA, Grid, and Options strategies with automated risk management.",
    category: "trading-bots",
    tags: ["DCA", "Grid", "Options", "Smart Terminal"],
    url: "https://3commas.io",
    affiliateUrl: "https://3commas.io/affiliate",
    pricing: "Free / $29-99/mo",
    rating: 4.5,
    featured: true,
  },
  {
    id: "pionex",
    name: "Pionex",
    description: "Built-in free AI trading bots with grid and arbitrage strategies. No subscription fees for bot usage.",
    category: "trading-bots",
    tags: ["Grid", "Arbitrage", "Free Bots"],
    url: "https://pionex.com",
    affiliateUrl: "https://pionex.com",
    pricing: "Free",
    rating: 4.3,
    featured: true,
  },
  {
    id: "cryptohopper",
    name: "Cryptohopper",
    description: "Cloud-based AI strategy designer with backtesting, simulation, and marketplace for trading strategies and signals.",
    category: "trading-bots",
    tags: ["Backtest", "Strategy Market", "Cloud"],
    url: "https://cryptohopper.com",
    affiliateUrl: "https://cryptohopper.com/affiliate-program",
    pricing: "$19-99/mo",
    rating: 4.4,
  },
  {
    id: "bitsgap",
    name: "Bitsgap",
    description: "Unified dashboard for multi-exchange management with AI grid bots and arbitrage detection.",
    category: "trading-bots",
    tags: ["Grid", "Arbitrage", "Multi-Exchange"],
    url: "https://bitsgap.com",
    affiliateUrl: "https://bitsgap.com/affiliate-program",
    pricing: "$29-149/mo",
    rating: 4.2,
  },
  {
    id: "coinrule",
    name: "Coinrule",
    description: "No-code strategy builder with visual rule creation. Perfect for beginners who want automation without coding.",
    category: "trading-bots",
    tags: ["No-Code", "Visual Builder", "Beginner"],
    url: "https://coinrule.com",
    pricing: "$0-499/mo",
    rating: 4.1,
  },
  {
    id: "tradesanta",
    name: "TradeSanta",
    description: "Simplified cloud automation for long/short strategies with AI assistance. Beginner-friendly interface.",
    category: "trading-bots",
    tags: ["Long/Short", "Cloud", "Beginner"],
    url: "https://tradesanta.com",
    pricing: "$15-35/mo",
    rating: 4.0,
  },
  {
    id: "cornix",
    name: "Cornix",
    description: "Telegram-integrated trading bot that auto-executes signals. Perfect for signal groups and copy trading.",
    category: "trading-bots",
    tags: ["Telegram", "Signal", "Auto-Execute"],
    url: "https://cornix.io",
    affiliateUrl: "https://cornix.io",
    pricing: "$24-59/mo",
    rating: 4.2,
  },
  {
    id: "wundertrading",
    name: "WunderTrading",
    description: "Automated trading with copy trading and TradingView signal integration. Social trading features.",
    category: "trading-bots",
    tags: ["Copy Trading", "TradingView", "Social"],
    url: "https://wundertrading.com",
    pricing: "$9.95-44.95/mo",
    rating: 4.0,
  },
  {
    id: "kryll",
    name: "Kryll",
    description: "Drag-and-drop strategy builder with no-code AI trading workflows. Visual flow editor.",
    category: "trading-bots",
    tags: ["Drag-Drop", "Visual", "No-Code"],
    url: "https://kryll.io",
    pricing: "Pay-per-use",
    rating: 4.1,
  },
  {
    id: "haasonline",
    name: "HaasOnline",
    description: "Advanced custom scripting with backtesting and high-frequency automation for professional traders.",
    category: "trading-bots",
    tags: ["Scripting", "HFT", "Professional"],
    url: "https://haasonline.com",
    pricing: "$9-99/mo",
    rating: 4.3,
  },
  {
    id: "algosone",
    name: "AlgosOne",
    description: "Fully autonomous AI trading platform with built-in risk rules and portfolio management.",
    category: "trading-bots",
    tags: ["Autonomous", "Risk Rules", "AI"],
    url: "https://algosone.ai",
    pricing: "Custom",
    rating: 3.9,
  },
  {
    id: "stoic",
    name: "Stoic",
    description: "AI-driven portfolio rebalancing and trading strategies with long-term focus.",
    category: "trading-bots",
    tags: ["Rebalancing", "Long-term", "AI"],
    url: "https://stoic.ai",
    pricing: "Free / Premium",
    rating: 4.0,
  },

  // On-Chain Analytics
  {
    id: "nansen",
    name: "Nansen",
    description: "500M+ labeled wallets, Smart Money tracking, and on-chain dashboards. Institutional-grade analytics.",
    category: "analytics",
    tags: ["Smart Money", "Labels", "Institutional"],
    url: "https://nansen.ai",
    affiliateUrl: "https://nansen.ai",
    pricing: "$150-3000/mo",
    rating: 4.6,
    featured: true,
  },
  {
    id: "arkham",
    name: "Arkham Intelligence",
    description: "800M+ labeled addresses with on-chain intelligence and wallet association identification.",
    category: "analytics",
    tags: ["Labels", "Wallet Tracking", "Intel"],
    url: "https://arkhamintelligence.com",
    pricing: "Free / $100+/mo",
    rating: 4.5,
  },
  {
    id: "dune",
    name: "Dune Analytics",
    description: "SQL-based blockchain data querying with custom dashboards. Community-driven analytics platform.",
    category: "analytics",
    tags: ["SQL", "Dashboards", "Community"],
    url: "https://dune.com",
    pricing: "Free / $300+/mo",
    rating: 4.7,
    featured: true,
  },
  {
    id: "glassnode",
    name: "Glassnode",
    description: "On-chain metrics and token performance analytics. Focus on institutional and macro analysis.",
    category: "analytics",
    tags: ["Metrics", "Macro", "Institutional"],
    url: "https://glassnode.com",
    pricing: "$29-799/mo",
    rating: 4.5,
  },
  {
    id: "intotheblock",
    name: "IntoTheBlock",
    description: "On-chain metrics with AI price predictions and holder analysis. Machine learning-driven insights.",
    category: "analytics",
    tags: ["AI Prediction", "Holder Analysis", "ML"],
    url: "https://intotheblock.com",
    pricing: "Free / Premium",
    rating: 4.3,
  },
  {
    id: "moralis",
    name: "Moralis",
    description: "Web3 API with real-time on-chain data streams. Developer-focused blockchain infrastructure.",
    category: "analytics",
    tags: ["API", "Real-time", "Developer"],
    url: "https://moralis.io",
    affiliateUrl: "https://start.moralismoney.com",
    pricing: "Free / $49+/mo",
    rating: 4.4,
  },
  {
    id: "footprint",
    name: "Footprint Analytics",
    description: "No-code blockchain data analysis with NFT and GameFi focus. Visual query builder.",
    category: "analytics",
    tags: ["No-Code", "NFT", "GameFi"],
    url: "https://footprint.network",
    pricing: "Free / Custom",
    rating: 4.2,
  },
  {
    id: "bubblemaps",
    name: "Bubblemaps",
    description: "Visual wallet clustering analysis to identify connected addresses and token distribution patterns.",
    category: "analytics",
    tags: ["Visualization", "Clustering", "Distribution"],
    url: "https://bubblemaps.io",
    pricing: "Free / Premium",
    rating: 4.1,
  },

  // Portfolio Management
  {
    id: "coinstats",
    name: "CoinStats",
    description: "Multi-platform portfolio tracking with AI market insights and price alerts. 1M+ users worldwide.",
    category: "portfolio",
    tags: ["Tracking", "AI Insights", "Alerts"],
    url: "https://coinstats.app",
    affiliateUrl: "https://coinstats.app/affiliate",
    pricing: "Free / $3.49+/mo",
    rating: 4.5,
    featured: true,
  },
  {
    id: "zapper",
    name: "Zapper",
    description: "One-stop DeFi aggregator for tokens, DeFi positions, and NFTs with interactive dashboard.",
    category: "portfolio",
    tags: ["DeFi", "NFT", "Aggregator"],
    url: "https://zapper.fi",
    pricing: "Free",
    rating: 4.4,
  },
  {
    id: "zerion",
    name: "Zerion",
    description: "Multi-chain portfolio with DeFi operations and social features. Web3-native experience.",
    category: "portfolio",
    tags: ["Multi-Chain", "DeFi", "Social"],
    url: "https://zerion.io",
    pricing: "Free / Premium",
    rating: 4.3,
  },
  {
    id: "debank",
    name: "DeBank",
    description: "DeFi portfolio tracking with on-chain activity monitoring. Most comprehensive DeFi dashboard.",
    category: "portfolio",
    tags: ["DeFi", "On-Chain", "Dashboard"],
    url: "https://debank.com",
    pricing: "Free",
    rating: 4.5,
  },
  {
    id: "nansen-portfolio",
    name: "Nansen Portfolio",
    description: "Portfolio view integrated with Smart Money data. See what whales are holding.",
    category: "portfolio",
    tags: ["Smart Money", "Whales", "Tracking"],
    url: "https://nansen.ai/portfolio",
    pricing: "Free / Premium",
    rating: 4.2,
  },
  {
    id: "delta",
    name: "Delta App",
    description: "Portfolio tracking across multiple asset classes including crypto, stocks, and forex.",
    category: "portfolio",
    tags: ["Multi-Asset", "Stocks", "Forex"],
    url: "https://delta.app",
    pricing: "Free / $8.99/mo",
    rating: 4.1,
  },

  // DeFi AI
  {
    id: "aixbt",
    name: "AIXBT",
    description: "Real-time crypto market intelligence AI agent on Virtuals protocol. Tracks 400+ KOLs and whale movements.",
    category: "defi",
    tags: ["AI Agent", "KOL Tracking", "Whales"],
    url: "https://aixbt.tech",
    pricing: "Token-based",
    rating: 4.4,
    featured: true,
  },
  {
    id: "derive",
    name: "Derive (ex-Lyra)",
    description: "Decentralized options and perpetuals with AI automation strategies. $1.5B+ cumulative volume.",
    category: "defi",
    tags: ["Options", "Perpetuals", "AI Strategy"],
    url: "https://derive.xyz",
    pricing: "Protocol Fees",
    rating: 4.3,
  },
  {
    id: "cod3x",
    name: "Cod3x",
    description: "AI agent for automated DeFi strategy execution across multiple protocols.",
    category: "defi",
    tags: ["AI Agent", "Automation", "Multi-Protocol"],
    url: "https://cod3x.org",
    pricing: "Token-based",
    rating: 4.0,
  },
  {
    id: "griffain",
    name: "Griffain",
    description: "AI-powered DeFi operations agent for complex yield strategies and portfolio optimization.",
    category: "defi",
    tags: ["AI Agent", "Yield", "Optimization"],
    url: "https://griffain.com",
    pricing: "Token-based",
    rating: 3.9,
  },
  {
    id: "hey-anon",
    name: "Hey Anon",
    description: "AI agent for DeFi automation with natural language commands. Execute complex DeFi ops with chat.",
    category: "defi",
    tags: ["AI Agent", "NLP", "Chat"],
    url: "https://heyanon.ai",
    pricing: "Token-based",
    rating: 4.1,
  },
  {
    id: "orbit",
    name: "Orbit",
    description: "Cross-chain DeFi AI tool for multi-chain yield optimization and bridging.",
    category: "defi",
    tags: ["Cross-Chain", "Yield", "Bridge"],
    url: "https://orbitprotocol.io",
    pricing: "Token-based",
    rating: 3.8,
  },
  {
    id: "neur",
    name: "Neur",
    description: "AI-driven DeFi analysis and strategy recommendation engine.",
    category: "defi",
    tags: ["AI Analysis", "Strategy", "Recommendation"],
    url: "https://neur.sh",
    pricing: "Token-based",
    rating: 3.9,
  },
  {
    id: "yieldforge",
    name: "YieldForge",
    description: "AI-powered DeFi yield optimization platform with risk-adjusted returns.",
    category: "defi",
    tags: ["Yield", "Optimization", "Risk"],
    url: "https://yieldforge.io",
    pricing: "Protocol Fees",
    rating: 4.0,
  },

  // Security & Audit
  {
    id: "certik",
    name: "CertiK Skynet",
    description: "AI Auditor with 88.6% vulnerability detection rate. Multi-stage verification with real-time risk monitoring.",
    category: "security",
    tags: ["AI Audit", "Vulnerability", "Monitoring"],
    url: "https://certik.com",
    pricing: "Enterprise",
    rating: 4.5,
  },
  {
    id: "goplus",
    name: "GoPlus Security",
    description: "Most integrated Web3 security API. Built into CoinGecko, OKX, Trust Wallet. Honey pot and blacklist detection.",
    category: "security",
    tags: ["API", "Honey Pot", "Blacklist"],
    url: "https://gopluslabs.io",
    pricing: "Free / API Credits",
    rating: 4.4,
    featured: true,
  },
  {
    id: "token-sniffer",
    name: "Token Sniffer",
    description: "Token security scanner with 47.9M tokens indexed. 6.08M flagged as scams. 0-100 safety score.",
    category: "security",
    tags: ["Scanner", "Score", "Scam Detection"],
    url: "https://tokensniffer.com",
    pricing: "Free / Premium",
    rating: 4.3,
  },
  {
    id: "defi-scanner",
    name: "De.Fi Scanner",
    description: "Contract auditing with REKT database and DeFi security scoring. Comprehensive risk assessment.",
    category: "security",
    tags: ["Audit", "REKT DB", "Scoring"],
    url: "https://de.fi/scanner",
    pricing: "Free / Premium",
    rating: 4.2,
  },
  {
    id: "revoke-cash",
    name: "Revoke.cash",
    description: "Token approval auditing and malicious approval revocation. Essential wallet hygiene tool.",
    category: "security",
    tags: ["Approval", "Revoke", "Wallet"],
    url: "https://revoke.cash",
    pricing: "Free",
    rating: 4.6,
  },

  // Sentiment & News
  {
    id: "lunarcrush",
    name: "LunarCrush",
    description: "Social media aggregation with sentiment analysis across Twitter, Reddit, YouTube. AI-driven signals.",
    category: "sentiment",
    tags: ["Sentiment", "Social", "Signals"],
    url: "https://lunarcrush.com",
    affiliateUrl: "https://lunarcrush.com/affiliate-program",
    pricing: "Free / $49+/mo",
    rating: 4.3,
  },
  {
    id: "santiment",
    name: "Santiment",
    description: "On-chain and social sentiment tracking with developer activity and whale behavior monitoring.",
    category: "sentiment",
    tags: ["On-Chain", "Whales", "Development"],
    url: "https://santiment.net",
    pricing: "$49-449/mo",
    rating: 4.2,
  },
  {
    id: "kaito",
    name: "Kaito AI",
    description: "AI-powered crypto information aggregator with Mindshare ranking and AI search engine.",
    category: "sentiment",
    tags: ["AI Search", "Mindshare", "Aggregator"],
    url: "https://kaito.ai",
    pricing: "Free / Premium",
    rating: 4.4,
  },
  {
    id: "messari",
    name: "Messari",
    description: "Crypto research with AI-driven industry analysis and institutional-grade data.",
    category: "sentiment",
    tags: ["Research", "Institutional", "Data"],
    url: "https://messari.io",
    pricing: "$29-1000+/mo",
    rating: 4.5,
  },

  // Chart & TA
  {
    id: "tradingview",
    name: "TradingView",
    description: "The most widely used charting platform with community AI/ML indicators and custom Pine Script.",
    category: "charting",
    tags: ["Charts", "Pine Script", "Community"],
    url: "https://tradingview.com",
    affiliateUrl: "https://tradingview.com/partner-program",
    pricing: "Free / $14.95-59.95/mo",
    rating: 4.8,
    featured: true,
  },
  {
    id: "trendspider",
    name: "TrendSpider",
    description: "Automated pattern recognition with trendlines and key levels. AI reduces subjective bias in TA.",
    category: "charting",
    tags: ["Pattern Recognition", "Trendlines", "Automation"],
    url: "https://trendspider.com",
    affiliateUrl: "https://trendspider.com",
    pricing: "$39-179/mo",
    rating: 4.4,
  },
  {
    id: "tickeron",
    name: "Tickeron",
    description: "AI pattern recognition and predictions across crypto, stocks, and ETFs. Machine learning TA.",
    category: "charting",
    tags: ["AI Prediction", "Pattern", "ML"],
    url: "https://tickeron.com",
    affiliateUrl: "https://tickeron.com",
    pricing: "$25-250/mo",
    rating: 4.1,
  },
  {
    id: "coinglass",
    name: "CoinGlass",
    description: "Futures and options market data with liquidation heatmaps. Essential for derivatives traders.",
    category: "charting",
    tags: ["Futures", "Liquidation", "Heatmap"],
    url: "https://coinglass.com",
    affiliateUrl: "https://coinglass.com/account/affiliate",
    pricing: "Free / Premium",
    rating: 4.5,
  },

  // Wallet & Key
  {
    id: "metamask",
    name: "MetaMask",
    description: "Leading Ethereum wallet with 650K+ assets supported. AI transaction monitoring and smart gas prediction.",
    category: "wallet",
    tags: ["Ethereum", "dApp", "Gas"],
    url: "https://metamask.io",
    pricing: "Free",
    rating: 4.5,
  },
  {
    id: "trust-wallet",
    name: "Trust Wallet",
    description: "Open-source multi-chain wallet with NFT support. AI portfolio performance and smart trading suggestions.",
    category: "wallet",
    tags: ["Multi-Chain", "NFT", "Open Source"],
    url: "https://trustwallet.com",
    pricing: "Free",
    rating: 4.4,
  },
  {
    id: "zengo",
    name: "Zengo",
    description: "Seedless wallet with facial biometric security. AI fraud detection and transaction monitoring.",
    category: "wallet",
    tags: ["Seedless", "Biometric", "Security"],
    url: "https://zengo.com",
    pricing: "Free / Premium",
    rating: 4.3,
  },
];
