export interface Tool {
  id: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  url: string;
  affiliateUrl?: string;
  pricing: string;
  rating: number;
  featured?: boolean;
}

export const categories = [
  { id: "all", name: "All Tools", count: 0 },
  { id: "trading-bots", name: "Trading Bots", count: 0 },
  { id: "analytics", name: "On-Chain Analytics", count: 0 },
  { id: "portfolio", name: "Portfolio Management", count: 0 },
  { id: "defi", name: "DeFi AI", count: 0 },
  { id: "security", name: "Security & Audit", count: 0 },
  { id: "sentiment", name: "Sentiment & News", count: 0 },
  { id: "charting", name: "Chart & TA", count: 0 },
  { id: "wallet", name: "Wallet & Key", count: 0 },
  { id: "nft", name: "NFT & Gaming", count: 0 },
  { id: "exchange", name: "CEX & DEX", count: 0 },
  { id: "news-data", name: "News & Data Feeds", count: 0 },
];

export const tools: Tool[] = [
  // ========== TRADING BOTS (50 tools) ==========
  {
    id: "3commas",
    name: "3Commas",
    description: "All-in-one trading platform with smart terminals and AI bots. Supports DCA, Grid, and Options strategies with automated risk management.",
    category: "trading-bots",
    tags: ["DCA", "Grid", "Options", "Smart Terminal"],
    url: "https://3commas.io",
    affiliateUrl: "https://3commas.io/affiliate",
    pricing: "Free / $29-99/mo",
    rating: 4.5,
    featured: true,
  },
  {
    id: "pionex",
    name: "Pionex",
    description: "Built-in free AI trading bots with grid and arbitrage strategies. No subscription fees for bot usage.",
    category: "trading-bots",
    tags: ["Grid", "Arbitrage", "Free Bots"],
    url: "https://pionex.com",
    affiliateUrl: "https://pionex.com/en/signup?r=affiliate",
    pricing: "Free",
    rating: 4.3,
    featured: true,
  },
  {
    id: "cryptohopper",
    name: "Cryptohopper",
    description: "Cloud-based AI strategy designer with backtesting, simulation, and marketplace for trading strategies and signals.",
    category: "trading-bots",
    tags: ["Backtest", "Strategy Market", "Cloud"],
    url: "https://cryptohopper.com",
    affiliateUrl: "https://www.cryptohopper.com/affiliate-program",
    pricing: "$19-99/mo",
    rating: 4.4,
  },
  {
    id: "bitsgap",
    name: "Bitsgap",
    description: "Unified dashboard for multi-exchange management with AI grid bots and arbitrage detection.",
    category: "trading-bots",
    tags: ["Grid", "Arbitrage", "Multi-Exchange"],
    url: "https://bitsgap.com",
    affiliateUrl: "https://bitsgap.com/affiliate-program",
    pricing: "$29-149/mo",
    rating: 4.2,
  },
  {
    id: "coinrule",
    name: "Coinrule",
    description: "No-code strategy builder with visual rule creation. Perfect for beginners who want automation without coding.",
    category: "trading-bots",
    tags: ["No-Code", "Visual Builder", "Beginner"],
    url: "https://coinrule.com",
    affiliateUrl: "https://coinrule.com/?ref=affiliate",
    pricing: "$0-499/mo",
    rating: 4.1,
  },
  {
    id: "tradesanta",
    name: "TradeSanta",
    description: "Simplified cloud automation for long/short strategies with AI assistance. Beginner-friendly interface.",
    category: "trading-bots",
    tags: ["Long/Short", "Cloud", "Beginner"],
    url: "https://tradesanta.com",
    pricing: "$15-35/mo",
    rating: 4.0,
  },
  {
    id: "cornix",
    name: "Cornix",
    description: "Telegram-integrated trading bot that auto-executes signals. Perfect for signal groups and copy trading.",
    category: "trading-bots",
    tags: ["Telegram", "Signal", "Auto-Execute"],
    url: "https://cornix.io",
    pricing: "$24-59/mo",
    rating: 4.2,
  },
  {
    id: "wundertrading",
    name: "WunderTrading",
    description: "Automated trading with copy trading and TradingView signal integration. Social trading features.",
    category: "trading-bots",
    tags: ["Copy Trading", "TradingView", "Social"],
    url: "https://wundertrading.com",
    pricing: "$9.95-44.95/mo",
    rating: 4.0,
  },
  {
    id: "kryll",
    name: "Kryll",
    description: "Drag-and-drop strategy builder with no-code AI trading workflows. Visual flow editor.",
    category: "trading-bots",
    tags: ["Drag-Drop", "Visual", "No-Code"],
    url: "https://kryll.io",
    pricing: "Pay-per-use",
    rating: 4.1,
  },
  {
    id: "haasonline",
    name: "HaasOnline",
    description: "Advanced custom scripting with backtesting and high-frequency automation for professional traders.",
    category: "trading-bots",
    tags: ["Scripting", "HFT", "Professional"],
    url: "https://haasonline.com",
    pricing: "$9.99-99.99/mo",
    rating: 4.3,
  },
  {
    id: "algosone",
    name: "AlgosOne",
    description: "Fully autonomous AI trading platform with built-in risk rules and portfolio management.",
    category: "trading-bots",
    tags: ["Autonomous", "Risk Rules", "AI"],
    url: "https://algosone.ai",
    pricing: "Custom",
    rating: 3.9,
  },
  {
    id: "stoic",
    name: "Stoic",
    description: "AI-driven portfolio rebalancing and trading strategies with long-term focus.",
    category: "trading-bots",
    tags: ["Rebalancing", "Long-term", "AI"],
    url: "https://stoic.ai",
    pricing: "Free / Premium",
    rating: 4.0,
  },
  {
    id: "mudrex",
    name: "Mudrex",
    description: "Curated bot marketplace with verified strategies. No coding required, copytrading enabled.",
    category: "trading-bots",
    tags: ["Marketplace", "Verified", "No-Code"],
    url: "https://mudrex.com",
    pricing: "$10-100/mo",
    rating: 4.2,
  },
  {
    id: "quadency",
    name: "Quadency",
    description: "Multi-exchange crypto platform with automated trading strategies and portfolio management.",
    category: "trading-bots",
    tags: ["Multi-Exchange", "Automation", "Portfolio"],
    url: "https://quadency.com",
    pricing: "Free / $29+/mo",
    rating: 4.1,
  },
  {
    id: "trality",
    name: "Trality",
    description: "Python-based bot creation with AI optimization. Free tier available for beginners.",
    category: "trading-bots",
    tags: ["Python", "AI Optimization", "Free Tier"],
    url: "https://trality.com",
    pricing: "Free / $9.99-49.99/mo",
    rating: 4.0,
  },
  {
    id: "goodcipher",
    name: "GoodCipher",
    description: "AI-powered trading signal generation with risk management. Focus on accuracy over frequency.",
    category: "trading-bots",
    tags: ["Signals", "Risk Management", "AI"],
    url: "https://goodcipher.com",
    pricing: "$49/mo",
    rating: 3.8,
  },
  {
    id: "cryptotrader",
    name: "CryptoTrader",
    description: "Cloud-based trading bot with technical indicator strategies. Supports multiple exchanges.",
    category: "trading-bots",
    tags: ["Cloud", "Technical", "Multi-Exchange"],
    url: "https://cryptotrader.org",
    pricing: "$19-89/mo",
    rating: 3.9,
  },
  {
    id: "gunbot",
    name: "Gunbot",
    description: "Desktop trading bot with 15+ strategies. One-time purchase option available.",
    category: "trading-bots",
    tags: ["Desktop", "One-time", "15+ Strategies"],
    url: "https://gunbot.com",
    pricing: "$49-199 one-time",
    rating: 4.0,
  },
  {
    id: "profitfarmers",
    name: "Profit Farmers",
    description: "Signal-based trading with copy-trading features. Focus on futures and spot signals.",
    category: "trading-bots",
    tags: ["Signals", "Futures", "Copy-Trading"],
    url: "https://profitfarmers.com",
    pricing: "$97/mo",
    rating: 4.1,
  },
  {
    id: "signalstack",
    name: "SignalStack",
    description: "Converts TradingView alerts into automated orders. No coding required.",
    category: "trading-bots",
    tags: ["TradingView", "Alerts", "No-Code"],
    url: "https://signalstack.com",
    pricing: "$99+/mo",
    rating: 4.2,
  },
  {
    id: "traders-post",
    name: "Trader's Post",
    description: "Automates TradingView strategy alerts to exchanges. Bridging analysis and execution.",
    category: "trading-bots",
    tags: ["TradingView", "Automation", "Bridge"],
    url: "https://traderspost.io",
    pricing: "Free / $29+/mo",
    rating: 4.0,
  },
  {
    id: "bitsmiley",
    name: "BitSmiley",
    description: "AI-driven DeFi lending and borrowing with smart risk assessment on Bitcoin network.",
    category: "trading-bots",
    tags: ["DeFi", "Lending", "Bitcoin"],
    url: "https://bitsmiley.io",
    pricing: "Protocol Fees",
    rating: 3.7,
  },
  {
    id: "napbots",
    name: "Napbots",
    description: "AI-powered crypto trading algorithms with unified interface. Backed by Napoleon Group.",
    category: "trading-bots",
    tags: ["AI Algorithms", "Unified", "Napoleon"],
    url: "https://napbots.com",
    pricing: "$29-99/mo",
    rating: 3.9,
  },
  {
    id: "mydnt",
    name: "MYDNT",
    description: "AI trading assistant with natural language commands. Execute trades via chat interface.",
    category: "trading-bots",
    tags: ["AI Assistant", "NLP", "Chat"],
    url: "https://mydnt.com",
    pricing: "Free / Premium",
    rating: 3.8,
  },
  {
    id: "zignaly",
    name: "Zignaly",
    description: "Copy trading platform with signal providers. Pay only when your copied trades are profitable.",
    category: "trading-bots",
    tags: ["Copy Trading", "Signals", "Profit-Share"],
    url: "https://zignaly.com",
    pricing: "Free / Profit Share",
    rating: 4.1,
  },
  {
    id: "altrady",
    name: "Altrady",
    description: "Multi-exchange crypto trading terminal with smart trading tools and portfolio management.",
    category: "trading-bots",
    tags: ["Terminal", "Multi-Exchange", "Smart Tools"],
    url: "https://altrady.com",
    pricing: "$19-79/mo",
    rating: 4.0,
  },
  {
    id: "crypto-herd",
    name: "CryptoHerd",
    description: "AI-powered social sentiment trading signals. Tracks retail and whale behavior.",
    category: "trading-bots",
    tags: ["Sentiment", "Social", "Whales"],
    url: "https://cryptoherd.com",
    pricing: "$29/mo",
    rating: 3.7,
  },
  {
    id: "tradescope",
    name: "TradeScope",
    description: "AI technical analysis and automated trading with pattern recognition across multiple timeframes.",
    category: "trading-bots",
    tags: ["Pattern Recognition", "Multi-Timeframe", "AI"],
    url: "https://tradescope.com",
    pricing: "$49-149/mo",
    rating: 3.9,
  },
  {
    id: "botcrypto",
    name: "Botcrypto",
    description: "French-developed trading bot with backtesting and visual strategy builder.",
    category: "trading-bots",
    tags: ["Backtest", "Visual", "European"],
    url: "https://botcrypto.com",
    pricing: "€29-99/mo",
    rating: 3.8,
  },
  {
    id: "leonardo-bot",
    name: "Leonardo Bot",
    description: "High-frequency trading bot for Binance and other major exchanges. Low latency execution.",
    category: "trading-bots",
    tags: ["HFT", "Binance", "Low Latency"],
    url: "https://leonardobot.com",
    pricing: "$39-99/mo",
    rating: 3.8,
  },
  {
    id: "cryptohopper-marketplace",
    name: "Cryptohopper Marketplace",
    description: "Buy and sell trading strategies. Community-driven strategy marketplace with performance tracking.",
    category: "trading-bots",
    tags: ["Marketplace", "Strategies", "Community"],
    url: "https://www.cryptohopper.com/marketplace",
    pricing: "Variable",
    rating: 4.0,
  },
  {
    id: "sigma-ai",
    name: "Sigma AI",
    description: "Machine learning trading signals with adaptive risk management. Self-learning algorithms.",
    category: "trading-bots",
    tags: ["Machine Learning", "Adaptive", "Self-Learning"],
    url: "https://sigmaai.trade",
    pricing: "$49-199/mo",
    rating: 3.9,
  },
  {
    id: "neurobot",
    name: "NeuroBot",
    description: "Neural network-based trading bot. Learns from market patterns and adapts strategies.",
    category: "trading-bots",
    tags: ["Neural Network", "Adaptive", "Learning"],
    url: "https://neurobot.ai",
    pricing: "$39-89/mo",
    rating: 3.8,
  },
  {
    id: "trade-machine-ai",
    name: "Trade Machine AI",
    description: "AI-powered trend prediction with automated entry/exit. Focus on major crypto pairs.",
    category: "trading-bots",
    tags: ["Trend Prediction", "Automated", "Major Pairs"],
    url: "https://trademachine.ai",
    pricing: "Custom",
    rating: 3.7,
  },
  {
    id: "bitcoin-pi-crypto",
    name: "Bitcoin Pi Crypto Trading Bot",
    description: "Automated trading bot specializing in Bitcoin and major altcoins. Simple setup.",
    category: "trading-bots",
    tags: ["Bitcoin", "Simple", "Major Alts"],
    url: "https://bitcoinpicrypto.com",
    pricing: "$29/mo",
    rating: 3.6,
  },
  {
    id: "trading-ops",
    name: "TradingOps",
    description: "Institutional-grade trading infrastructure with AI optimization. For serious traders.",
    category: "trading-bots",
    tags: ["Institutional", "Infrastructure", "AI"],
    url: "https://tradingops.com",
    pricing: "Custom",
    rating: 4.0,
  },
  {
    id: "flash-crypto-bot",
    name: "Flash Crypto Bot",
    description: "Arbitrage trading bot scanning multiple exchanges for price differences.",
    category: "trading-bots",
    tags: ["Arbitrage", "Multi-Exchange", "Scanner"],
    url: "https://flashcryptobot.com",
    pricing: "$49-149/mo",
    rating: 3.7,
  },
  {
    id: "crypto-base-bot",
    name: "CryptoBaseBot",
    description: "Grid trading specialist with AI-optimized grid placement. Maximize sideways market profits.",
    category: "trading-bots",
    tags: ["Grid", "Sideways", "AI-Optimized"],
    url: "https://cryptobasebot.com",
    pricing: "$29-79/mo",
    rating: 3.9,
  },
  {
    id: "smart-auto-trader",
    name: "Smart Auto Trader",
    description: "AI-driven automated trading with dynamic stop-loss and take-profit levels.",
    category: "trading-bots",
    tags: ["Dynamic SL/TP", "AI", "Automated"],
    url: "https://smartautotrader.com",
    pricing: "$39/mo",
    rating: 3.8,
  },
  {
    id: "trade-alert-bot",
    name: "Trade Alert Bot",
    description: "Telegram and Discord alert bot with AI-powered signal generation.",
    category: "trading-bots",
    tags: ["Telegram", "Discord", "Alerts"],
    url: "https://tradealertbot.com",
    pricing: "Free / $19/mo",
    rating: 3.7,
  },
  {
    id: "crypto-scalper",
    name: "CryptoScalper",
    description: "High-frequency scalping bot for crypto futures. AI detects micro-trends for quick profits.",
    category: "trading-bots",
    tags: ["Scalping", "Futures", "HFT"],
    url: "https://cryptoscalper.com",
    pricing: "$49-199/mo",
    rating: 3.8,
  },
  {
    id: "arbibot",
    name: "ArbiBot",
    description: "Specialized arbitrage bot with flash loan integration. Cross-chain arbitrage opportunities.",
    category: "trading-bots",
    tags: ["Arbitrage", "Flash Loan", "Cross-Chain"],
    url: "https://arbibot.io",
    pricing: "$39-99/mo",
    rating: 3.9,
  },
  {
    id: "bot-wisdom",
    name: "BotWisdom",
    description: "AI trading bot with wisdom-based decision making. Combines technical and fundamental analysis.",
    category: "trading-bots",
    tags: ["AI", "Technical", "Fundamental"],
    url: "https://botwisdom.com",
    pricing: "$29-69/mo",
    rating: 3.7,
  },
  {
    id: "crypto-autotrader",
    name: "Crypto AutoTrader",
    description: "Automated trading with preset strategies. Beginner-friendly with guided setup.",
    category: "trading-bots",
    tags: ["Automated", "Beginner", "Guided"],
    url: "https://cryptoautotrader.com",
    pricing: "$19-49/mo",
    rating: 3.8,
  },
  {
    id: "ai-crypto-bot",
    name: "AI Crypto Bot",
    description: "Next-gen AI trading bot with deep learning. Continuously improves trading strategies.",
    category: "trading-bots",
    tags: ["Deep Learning", "Continuous", "Improvement"],
    url: "https://aicryptobot.com",
    pricing: "$49-149/mo",
    rating: 3.9,
  },
  {
    id: "bitscreener-bot",
    name: "BitScreener Bot",
    description: "AI-powered market scanner with automated trading signals. Real-time opportunity detection.",
    category: "trading-bots",
    tags: ["Scanner", "Signals", "Real-time"],
    url: "https://bitscreener.com",
    pricing: "Free / $29/mo",
    rating: 4.0,
  },
  {
    id: "trade-alphas",
    name: "Trade Alphas",
    description: "Crowdsourced trading algorithms with AI performance ranking. Community-vetted strategies.",
    category: "trading-bots",
    tags: ["Crowdsourced", "Ranking", "Community"],
    url: "https://tradealphas.com",
    pricing: "Free / Profit Share",
    rating: 3.9,
  },
  {
    id: "crypto-robot",
    name: "Crypto Robot",
    description: "Automated trading robot with AI strategy optimization. Supports major exchanges.",
    category: "trading-bots",
    tags: ["Robot", "AI Optimization", "Major Exchanges"],
    url: "https://cryptorobot.com",
    pricing: "$29-99/mo",
    rating: 3.7,
  },
  {
    id: "pionex-grid",
    name: "Pionex Grid Bot",
    description: "Specialized grid trading bot from Pionex. Optimized for sideways and volatile markets.",
    category: "trading-bots",
    tags: ["Grid", "Sideways", "Volatile"],
    url: "https://pionex.com/en/grid-trading-bot",
    pricing: "Free",
    rating: 4.2,
  },
  {
    id: "octobot",
    name: "OctoBot",
    description: "Open-source trading bot with AI strategy optimization. Fully customizable and free to run.",
    category: "trading-bots",
    tags: ["Open-Source", "Customizable", "Free"],
    url: "https://www.octobot.online",
    pricing: "Free / Cloud $29+/mo",
    rating: 4.0,
  },
  // ========== ON-CHAIN ANALYTICS (50 tools) ==========
  {
    id: "nansen",
    name: "Nansen",
    description: "500M+ labeled wallets, Smart Money tracking, and on-chain dashboards. Institutional-grade analytics.",
    category: "analytics",
    tags: ["Smart Money", "Labels", "Institutional"],
    url: "https://nansen.ai",
    affiliateUrl: "https://nansen.ai/referral",
    pricing: "$150-3000/mo",
    rating: 4.6,
    featured: true,
  },
  {
    id: "arkham",
    name: "Arkham Intelligence",
    description: "800M+ labeled addresses with on-chain intelligence and wallet association identification.",
    category: "analytics",
    tags: ["Labels", "Wallet Tracking", "Intel"],
    url: "https://arkhamintelligence.com",
    pricing: "Free / $100+/mo",
    rating: 4.5,
  },
  {
    id: "dune",
    name: "Dune Analytics",
    description: "SQL-based blockchain data querying with custom dashboards. Community-driven analytics platform.",
    category: "analytics",
    tags: ["SQL", "Dashboards", "Community"],
    url: "https://dune.com",
    affiliateUrl: "https://dune.com/referral",
    pricing: "Free / $300+/mo",
    rating: 4.7,
    featured: true,
  },
  {
    id: "glassnode",
    name: "Glassnode",
    description: "On-chain metrics and token performance analytics. Focus on institutional and macro analysis.",
    category: "analytics",
    tags: ["Metrics", "Macro", "Institutional"],
    url: "https://glassnode.com",
    pricing: "$29-799/mo",
    rating: 4.5,
  },
  {
    id: "intotheblock",
    name: "IntoTheBlock",
    description: "On-chain metrics with AI price predictions and holder analysis. Machine learning-driven insights.",
    category: "analytics",
    tags: ["AI Prediction", "Holder Analysis", "ML"],
    url: "https://intotheblock.com",
    pricing: "Free / Premium",
    rating: 4.3,
  },
  {
    id: "moralis",
    name: "Moralis",
    description: "Web3 API with real-time on-chain data streams. Developer-focused blockchain infrastructure.",
    category: "analytics",
    tags: ["API", "Real-time", "Developer"],
    url: "https://moralis.io",
    affiliateUrl: "https://start.moralismoney.com",
    pricing: "Free / $49+/mo",
    rating: 4.4,
  },
  {
    id: "footprint",
    name: "Footprint Analytics",
    description: "No-code blockchain data analysis with NFT and GameFi focus. Visual query builder.",
    category: "analytics",
    tags: ["No-Code", "NFT", "GameFi"],
    url: "https://footprint.network",
    pricing: "Free / Custom",
    rating: 4.2,
  },
  {
    id: "bubblemaps",
    name: "Bubblemaps",
    description: "Visual wallet clustering analysis to identify connected addresses and token distribution patterns.",
    category: "analytics",
    tags: ["Visualization", "Clustering", "Distribution"],
    url: "https://bubblemaps.io",
    pricing: "Free / Premium",
    rating: 4.1,
  },
  {
    id: "tokenterminal",
    name: "Token Terminal",
    description: "Financial metrics for crypto protocols. Revenue, earnings, and valuation data.",
    category: "analytics",
    tags: ["Financial", "Revenue", "Valuation"],
    url: "https://tokenterminal.com",
    pricing: "Free / $99+/mo",
    rating: 4.3,
  },
  {
    id: "defillama",
    name: "DeFi Llama",
    description: "Largest TVL aggregator for DeFi protocols. Open-source and community-maintained.",
    category: "analytics",
    tags: ["TVL", "DeFi", "Open-Source"],
    url: "https://defillama.com",
    pricing: "Free",
    rating: 4.8,
  },
  {
    id: "defiwonderland",
    name: "DeFi Wonderland",
    description: "DeFi analytics and simulation tools. Fork analysis and protocol comparison.",
    category: "analytics",
    tags: ["Simulation", "Fork Analysis", "Comparison"],
    url: "https://defiwonderland.com",
    pricing: "Free / Premium",
    rating: 3.9,
  },
  {
    id: "nansen-query",
    name: "Nansen Query",
    description: "Advanced SQL querying on Nansen's labeled on-chain data. For power users.",
    category: "analytics",
    tags: ["SQL", "Advanced", "Power User"],
    url: "https://nansen.ai/query",
    pricing: "Included in Nansen Plans",
    rating: 4.4,
  },
  {
    id: "chainalysis",
    name: "Chainalysis",
    description: "Blockchain analysis and investigation platform. Industry standard for compliance and investigation.",
    category: "analytics",
    tags: ["Investigation", "Compliance", "Enterprise"],
    url: "https://chainalysis.com",
    pricing: "Enterprise",
    rating: 4.5,
  },
  {
    id: "elliptic",
    name: "Elliptic",
    description: "Cryptoasset risk management and investigation. Used by governments and financial institutions.",
    category: "analytics",
    tags: ["Risk", "Investigation", "Institutional"],
    url: "https://elliptic.co",
    pricing: "Enterprise",
    rating: 4.4,
  },
  {
    id: "crystal-blockchain",
    name: "Crystal Blockchain",
    description: "Blockchain analytics for AML and compliance. Visual investigation tools.",
    category: "analytics",
    tags: ["AML", "Compliance", "Visual"],
    url: "https://crystalblockchain.com",
    pricing: "Enterprise",
    rating: 4.2,
  },
  {
    id: "oklink",
    name: "OKLink",
    description: "Multi-chain blockchain explorer and analytics platform by OKX. Free on-chain data.",
    category: "analytics",
    tags: ["Explorer", "Multi-Chain", "Free"],
    url: "https://www.oklink.com",
    pricing: "Free / API Credits",
    rating: 4.3,
  },
  {
    id: "etherscan",
    name: "Etherscan",
    description: "The leading Ethereum blockchain explorer. Transaction tracking, contract verification, and API access.",
    category: "analytics",
    tags: ["Ethereum", "Explorer", "API"],
    url: "https://etherscan.io",
    pricing: "Free / $499+/mo API",
    rating: 4.8,
  },
  {
    id: "blockchain-com-explorer",
    name: "Blockchain.com Explorer",
    description: "Popular blockchain explorer for Bitcoin, Ethereum, and more. Simple interface.",
    category: "analytics",
    tags: ["Bitcoin", "Ethereum", "Simple"],
    url: "https://blockchain.com/explorer",
    pricing: "Free",
    rating: 4.5,
  },
  {
    id: "solscan",
    name: "Solscan",
    description: "Solana blockchain explorer with detailed transaction and account information.",
    category: "analytics",
    tags: ["Solana", "Explorer", "Account"],
    url: "https://solscan.io",
    pricing: "Free / API",
    rating: 4.6,
  },
  {
    id: "polygonscan",
    name: "Polygonscan",
    description: "Official Polygon blockchain explorer. Track transactions, contracts, and tokens.",
    category: "analytics",
    tags: ["Polygon", "Explorer", "Contracts"],
    url: "https://polygonscan.com",
    pricing: "Free / API",
    rating: 4.5,
  },
  {
    id: "bscscan",
    name: "BscScan",
    description: "BNB Smart Chain explorer. Most popular BSC block explorer with API access.",
    category: "analytics",
    tags: ["BSC", "Explorer", "API"],
    url: "https://bscscan.com",
    pricing: "Free / API",
    rating: 4.6,
  },
  {
    id: "snowtrace",
    name: "SnowTrace",
    description: "Avalanche C-Chain explorer (powered by Etherscan). Fast and reliable.",
    category: "analytics",
    tags: ["Avalanche", "Explorer", "C-Chain"],
    url: "https://snowtrace.io",
    pricing: "Free / API",
    rating: 4.4,
  },
  {
    id: "arbiscan",
    name: "Arbiscan",
    description: "Arbitrum One blockchain explorer. Track L2 transactions and smart contracts.",
    category: "analytics",
    tags: ["Arbitrum", "L2", "Explorer"],
    url: "https://arbiscan.io",
    pricing: "Free / API",
    rating: 4.5,
  },
  {
    id: "optimistic-etherscan",
    name: "Optimistic Etherscan",
    description: "Optimism L2 blockchain explorer. Fast transactions with low fees tracking.",
    category: "analytics",
    tags: ["Optimism", "L2", "Low Fees"],
    url: "https://optimistic.etherscan.io",
    pricing: "Free / API",
    rating: 4.3,
  },
  {
    id: "basescan",
    name: "BaseScan",
    description: "Base L2 blockchain explorer by Coinbase. Growing ecosystem tracking.",
    category: "analytics",
    tags: ["Base", "L2", "Coinbase"],
    url: "https://basescan.org",
    pricing: "Free / API",
    rating: 4.4,
  },
  {
    id: "blockscout",
    name: "Blockscout",
    description: "Open-source blockchain explorer for Ethereum-based networks. Self-hosted option available.",
    category: "analytics",
    tags: ["Open-Source", "Ethereum", "Self-Hosted"],
    url: "https://blockscout.com",
    pricing: "Free / Self-Hosted",
    rating: 4.2,
  },
  {
    id: "bitquery",
    name: "Bitquery",
    description: "Blockchain data API with GraphQL interface. Query any on-chain data with simple queries.",
    category: "analytics",
    tags: ["API", "GraphQL", "Multi-Chain"],
    url: "https://bitquery.io",
    pricing: "Free / $299+/mo",
    rating: 4.3,
  },
  {
    id: "covalent",
    name: "Covalent",
    description: "Unified API bringing visibility to billions of blockchain data points. No-code data access.",
    category: "analytics",
    tags: ["API", "Unified", "No-Code"],
    url: "https://www.covalenthq.com",
    pricing: "Free / $200+/mo",
    rating: 4.4,
  },
  {
    id: "the-graph",
    name: "The Graph",
    description: "Indexing protocol for querying blockchain data with GraphQL. Decentralized data access.",
    category: "analytics",
    tags: ["Indexing", "GraphQL", "Decentralized"],
    url: "https://thegraph.com",
    pricing: "Free / Pay-per-query",
    rating: 4.5,
  },
  {
    id: "alchemy-nft",
    name: "Alchemy NFT API",
    description: "Comprehensive NFT data API. Fetch metadata, ownership, and sales history across chains.",
    category: "analytics",
    tags: ["NFT", "API", "Multi-Chain"],
    url: "https://www.alchemy.com/nft-api",
    pricing: "Free / $199+/mo",
    rating: 4.4,
  },
  {
    id: "reservoir",
    name: "Reservoir",
    description: "NFT marketplace aggregation API. Unified access to NFT liquidity across all major marketplaces.",
    category: "analytics",
    tags: ["NFT", "Aggregation", "API"],
    url: "https://reservoir.tools",
    pricing: "Free / Enterprise",
    rating: 4.2,
  },
  {
    id: "dappradar",
    name: "DappRadar",
    description: "DApp discovery and analytics platform. Track DAU, TVL, and volume across all protocols.",
    category: "analytics",
    tags: ["DApp", "Discovery", "Analytics"],
    url: "https://dappradar.com",
    pricing: "Free / Pro",
    rating: 4.5,
  },
  {
    id: "messari",
    name: "Messari",
    description: "Crypto research with AI-driven industry analysis and institutional-grade data.",
    category: "analytics",
    tags: ["Research", "Institutional", "Data"],
    url: "https://messari.io",
    pricing: "$29-1000+/mo",
    rating: 4.5,
  },
  {
    id: "coingecko",
    name: "CoinGecko",
    description: "Largest crypto data aggregator. Prices, market cap, on-chain analytics, and research reports.",
    category: "analytics",
    tags: ["Data Aggregator", "Prices", "Research"],
    url: "https://coingecko.com",
    affiliateUrl: "https://coingecko.com/partner-program",
    pricing: "Free / $32.5+/mo",
    rating: 4.7,
  },
  {
    id: "coinmarketcap",
    name: "CoinMarketCap",
    description: "Most referenced crypto price tracking website. Rankings, portfolio, and educational content.",
    category: "analytics",
    tags: ["Prices", "Rankings", "Education"],
    url: "https://coinmarketcap.com",
    pricing: "Free / $19.99+/mo",
    rating: 4.6,
  },
  {
    id: "cryptocompare",
    name: "CryptoCompare",
    description: "Institutional-grade crypto data and pricing. API used by financial institutions globally.",
    category: "analytics",
    tags: ["Institutional", "API", "Pricing"],
    url: "https://cryptocompare.com",
    pricing: "Free / Enterprise",
    rating: 4.3,
  },
  {
    id: "kaiko",
    name: "Kaiko",
    description: "Institutional crypto market data. Historical and real-time data for enterprise clients.",
    category: "analytics",
    tags: ["Institutional", "Historical", "Enterprise"],
    url: "https://kaiko.com",
    pricing: "Enterprise",
    rating: 4.4,
  },
  {
    id: "nomics",
    name: "Nomics",
    description: "Professional-grade crypto market data API. Transparent methodology and institutional quality.",
    category: "analytics",
    tags: ["API", "Professional", "Transparent"],
    url: "https://nomics.com",
    pricing: "Free / $249+/mo",
    rating: 4.2,
  },
  {
    id: "coinAPI",
    name: "CoinAPI",
    description: "Real-time and historical crypto market data API. Covers 350+ exchanges and 20K+ symbols.",
    category: "analytics",
    tags: ["API", "Real-time", "350+ Exchanges"],
    url: "https://coinapi.io",
    pricing: "Free / $199+/mo",
    rating: 4.3,
  },
  {
    id: "coinalyze",
    name: "Coinalyze",
    description: "Futures trading data with long/short ratios and funding rates. Essential for derivatives traders.",
    category: "analytics",
    tags: ["Futures", "Long/Short", "Funding"],
    url: "https://coinalyze.net",
    pricing: "Free / $29+/mo",
    rating: 4.4,
  },
  {
    id: "skew",
    name: "Skew (now Coinbase)",
    description: "Crypto derivatives analytics now part of Coinbase. Professional-grade futures and options data.",
    category: "analytics",
    tags: ["Derivatives", "Professional", "Coinbase"],
    url: "https://www.skew.com",
    pricing: "Enterprise",
    rating: 4.3,
  },
  {
    id: "bybt",
    name: "Bybt (CoinGlass)",
    description: "Comprehensive futures and options data. Liquidation maps and open interest tracking.",
    category: "analytics",
    tags: ["Futures", "Liquidation", "Open Interest"],
    url: "https://bybt.com",
    pricing: "Free / Premium",
    rating: 4.5,
  },
  {
    id: "whale-alert",
    name: "Whale Alert",
    description: "Real-time large transaction tracking across 50+ blockchains. Know when whales move.",
    category: "analytics",
    tags: ["Whales", "Real-time", "50+ Chains"],
    url: "https://whale-alert.io",
    pricing: "Free / $9.99+/mo",
    rating: 4.2,
  },
  {
    id: "whale-map",
    name: "Whale Map",
    description: "Bitcoin whale wallet tracking with heatmaps. Visual representation of large holder activity.",
    category: "analytics",
    tags: ["Bitcoin", "Whales", "Heatmap"],
    url: "https://whalemap.com",
    pricing: "Free / Premium",
    rating: 4.1,
  },
  {
    id: "supply-shock",
    name: "Supply Shock",
    description: "Bitcoin supply analysis tool. Track long-term holder supply and scarcity metrics.",
    category: "analytics",
    tags: ["Bitcoin", "Supply", "Scarcity"],
    url: "https://supplyshock.io",
    pricing: "Free / $19/mo",
    rating: 4.0,
  },
  {
    id: "check-on-chain",
    name: "Check On-Chain",
    description: "Simple on-chain metrics dashboard. Focus on Bitcoin and Ethereum key indicators.",
    category: "analytics",
    tags: ["Bitcoin", "Ethereum", "Simple"],
    url: "https://checkonchain.com",
    pricing: "Free",
    rating: 3.9,
  },
  {
    id: "lookintobitcoin",
    name: "Look Into Bitcoin",
    description: "Bitcoin on-chain analytics with beautiful charts. HODL waves, RHODL ratio, and more.",
    category: "analytics",
    tags: ["Bitcoin", "Charts", "HODL"],
    url: "https://lookintobitcoin.com",
    pricing: "Free / $19/mo",
    rating: 4.3,
  },
  {
    id: "woocharts",
    name: "WooCharts",
    description: "Advanced on-chain charts with customizable indicators. Professional-grade analytics.",
    category: "analytics",
    tags: ["Charts", "Customizable", "Professional"],
    url: "https://woocharts.com",
    pricing: "Free / $29/mo",
    rating: 4.1,
  },
  {
    id: "studio-shodell",
    name: "Studio Shodell",
    description: "On-chain narrative tracking and wallet profiling. Understand capital flows and narratives.",
    category: "analytics",
    tags: ["Narrative", "Wallet Profile", "Capital Flow"],
    url: "https://studioshodell.com",
    pricing: "Free / Premium",
    rating: 3.9,
  },
  {
    id: "address-toxicity",
    name: "Address Toxicity",
    description: "Wallet risk scoring based on transaction history. Detect high-risk addresses.",
    category: "analytics",
    tags: ["Risk Score", "Wallet", "Detection"],
    url: "https://addresstoxicity.com",
    pricing: "Free / API",
    rating: 3.8,
  },
  // ========== PORTFOLIO MANAGEMENT (40 tools) ==========
  {
    id: "coinstats",
    name: "CoinStats",
    description: "Multi-platform portfolio tracking with AI market insights and price alerts. 1M+ users worldwide.",
    category: "portfolio",
    tags: ["Tracking", "AI Insights", "Alerts"],
    url: "https://coinstats.app",
    affiliateUrl: "https://coinstats.app/affiliate",
    pricing: "Free / $3.49+/mo",
    rating: 4.5,
    featured: true,
  },
  {
    id: "zapper",
    name: "Zapper",
    description: "One-stop DeFi aggregator for tokens, DeFi positions, and NFTs with interactive dashboard.",
    category: "portfolio",
    tags: ["DeFi", "NFT", "Aggregator"],
    url: "https://zapper.fi",
    pricing: "Free",
    rating: 4.4,
  },
  {
    id: "zerion",
    name: "Zerion",
    description: "Multi-chain portfolio with DeFi operations and social features. Web3-native experience.",
    category: "portfolio",
    tags: ["Multi-Chain", "DeFi", "Social"],
    url: "https://zerion.io",
    pricing: "Free / Premium",
    rating: 4.3,
  },
  {
    id: "debank",
    name: "DeBank",
    description: "DeFi portfolio tracking with on-chain activity monitoring. Most comprehensive DeFi dashboard.",
    category: "portfolio",
    tags: ["DeFi", "On-Chain", "Dashboard"],
    url: "https://debank.com",
    pricing: "Free",
    rating: 4.5,
  },
  {
    id: "nansen-portfolio",
    name: "Nansen Portfolio",
    description: "Portfolio view integrated with Smart Money data. See what whales are holding.",
    category: "portfolio",
    tags: ["Smart Money", "Whales", "Tracking"],
    url: "https://nansen.ai/portfolio",
    pricing: "Free / Premium",
    rating: 4.2,
  },
  {
    id: "delta",
    name: "Delta App",
    description: "Portfolio tracking across multiple asset classes including crypto, stocks, and forex.",
    category: "portfolio",
    tags: ["Multi-Asset", "Stocks", "Forex"],
    url: "https://delta.app",
    pricing: "Free / $8.99/mo",
    rating: 4.1,
  },
  {
    id: "cointracker",
    name: "CoinTracker",
    description: "Portfolio tracking with tax calculation. Syncs with 500+ wallets and exchanges.",
    category: "portfolio",
    tags: ["Tracking", "Tax", "500+ Integrations"],
    url: "https://www.cointracker.io",
    affiliateUrl: "https://www.cointracker.io/referral",
    pricing: "Free / $59+/mo",
    rating: 4.4,
  },
  {
    id: "koinly",
    name: "Koinly",
    description: "Crypto tax calculator with portfolio tracking. Supports 800+ exchanges and wallets.",
    category: "portfolio",
    tags: ["Tax", "Portfolio", "800+ Integrations"],
    url: "https://koinly.io",
    affiliateUrl: "https://koinly.io/affiliate",
    pricing: "Free / $49+/mo",
    rating: 4.5,
  },
  {
    id: "cryptotaxcalculator",
    name: "CryptoTaxCalculator",
    description: "Advanced crypto tax calculation with DeFi and NFT support. Used by professionals.",
    category: "portfolio",
    tags: ["Tax", "DeFi", "NFT"],
    url: "https://cryptotaxcalculator.io",
    pricing: "$49-499/yr",
    rating: 4.3,
  },
  {
    id: "tokentax",
    name: "TokenTax",
    description: "Crypto tax software with full-service CPA support. Import trades from any exchange.",
    category: "portfolio",
    tags: ["Tax", "CPA", "Full-Service"],
    url: "https://tokentax.co",
    pricing: "$65-999/yr",
    rating: 4.2,
  },
  {
    id: "accointing",
    name: "Accointing",
    description: "Portfolio tracking and tax reporting in one platform. Intuitive interface.",
    category: "portfolio",
    tags: ["Tracking", "Tax", "Intuitive"],
    url: "https://accointing.com",
    pricing: "Free / $79+/yr",
    rating: 4.0,
  },
  {
    id: "blockpit",
    name: "Blockpit",
    description: "European crypto tax calculator with portfolio tracking. Compliant with EU tax laws.",
    category: "portfolio",
    tags: ["Tax", "EU", "Compliant"],
    url: "https://blockpit.io",
    pricing: "€0-399/yr",
    rating: 4.1,
  },
  {
    id: "cointracking",
    name: "CoinTracking",
    description: "One of the oldest portfolio trackers with tax reporting. 75+ exchanges supported.",
    category: "portfolio",
    tags: ["Tracking", "Tax", "75+ Exchanges"],
    url: "https://cointracking.info",
    pricing: "Free / €149+/yr",
    rating: 4.3,
  },
  {
    id: "rotki",
    name: "Rotki",
    description: "Open-source portfolio tracking with privacy focus. Local data storage, no cloud required.",
    category: "portfolio",
    tags: ["Open-Source", "Privacy", "Local"],
    url: "https://rotki.com",
    pricing: "Free / €12+/mo",
    rating: 4.4,
  },
  {
    id: "exodus",
    name: "Exodus Portfolio",
    description: "Beautiful multi-asset wallet with built-in portfolio tracking and exchange.",
    category: "portfolio",
    tags: ["Wallet", "Multi-Asset", "Beautiful"],
    url: "https://exodus.com",
    pricing: "Free",
    rating: 4.5,
  },
  {
    id: "edge-app",
    name: "Edge App",
    description: "Multi-currency wallet with portfolio tracking and built-in exchange features.",
    category: "portfolio",
    tags: ["Wallet", "Multi-Currency", "Exchange"],
    url: "https://edge.app",
    pricing: "Free",
    rating: 4.2,
  },
  {
    id: "ledger-live",
    name: "Ledger Live",
    description: "Portfolio management for Ledger hardware wallet. Secure tracking with DeFi integration.",
    category: "portfolio",
    tags: ["Hardware", "Secure", "DeFi"],
    url: "https://www.ledger.com/ledger-live",
    pricing: "Free with Device",
    rating: 4.4,
  },
  {
    id: "trezor-suite",
    name: "Trezor Suite",
    description: "Portfolio and device management for Trezor hardware wallets. Privacy-focused.",
    category: "portfolio",
    tags: ["Hardware", "Privacy", "Suite"],
    url: "https://suite.trezor.io",
    pricing: "Free with Device",
    rating: 4.3,
  },
  {
    id: "blockfolio",
    name: "Blockfolio (FTX App)",
    description: "Popular mobile portfolio tracker with social features. Now part of FTX ecosystem.",
    category: "portfolio",
    tags: ["Mobile", "Social", "FTX"],
    url: "https://blockfolio.com",
    pricing: "Free",
    rating: 4.0,
  },
  {
    id: "binance-portfolio",
    name: "Binance Portfolio",
    description: "Native portfolio tracking within Binance exchange. Real-time P&L and allocation view.",
    category: "portfolio",
    tags: ["Binance", "Native", "Real-time"],
    url: "https://www.binance.com/en/portfolio",
    pricing: "Free for Binance Users",
    rating: 4.2,
  },
  {
    id: "okx-portfolio",
    name: "OKX Portfolio",
    description: "Unified portfolio view across CeFi and DeFi. Track DeFi positions directly.",
    category: "portfolio",
    tags: ["OKX", "CeFi/DeFi", "Unified"],
    url: "https://www.okx.com/web3",
    pricing: "Free for OKX Users",
    rating: 4.3,
  },
  {
    id: "1inch-portfolio",
    name: "1inch Portfolio",
    description: "DeFi portfolio tracking via 1inch. Aggregates positions across multiple DeFi protocols.",
    category: "portfolio",
    tags: ["DeFi", "Aggregator", "Multi-Protocol"],
    url: "https://1inch.io",
    pricing: "Free",
    rating: 4.1,
  },
  {
    id: "apy-vision",
    name: "APY.vision",
    description: "Impermanent loss tracking for DeFi LPs. Monitor Uniswap, Curve, and other LP positions.",
    category: "portfolio",
    tags: ["IL Tracking", "LP", "Uniswap"],
    url: "https://apy.vision",
    pricing: "Free / $49+/mo",
    rating: 4.3,
  },
  {
    id: "farmdefi",
    name: "FarmDeFi",
    description: "Yield farming dashboard with IL simulation. Optimize LP positions across DeFi.",
    category: "portfolio",
    tags: ["Yield", "IL Simulation", "LP"],
    url: "https://farmdefi.com",
    pricing: "Free / Premium",
    rating: 3.9,
  },
  {
    id: "defi-pulse",
    name: "DeFi Pulse",
    description: "DeFi sector tracking with historical TVL data. Originally created DeFi Pulse Index.",
    category: "portfolio",
    tags: ["TVL", "Historical", "Index"],
    url: "https://defipulse.com",
    pricing: "Free",
    rating: 4.2,
  },
  {
    id: "zerion-tax",
    name: "Zerion Tax",
    description: "Tax reporting built into Zerion portfolio tracker. Export transactions for tax filing.",
    category: "portfolio",
    tags: ["Tax", "Portfolio", "Export"],
    url: "https://zerion.io/tax",
    pricing: "Free / Premium",
    rating: 4.0,
  },
  {
    id: "kattana",
    name: "Kattana",
    description: "Multi-chain DeFi portfolio with advanced trading terminal. Professional DeFi interface.",
    category: "portfolio",
    tags: ["Multi-Chain", "DeFi", "Terminal"],
    url: "https://kattana.io",
    pricing: "Free / $29/mo",
    rating: 3.9,
  },
  {
    id: "aseto",
    name: "Aseto",
    description: "AI-powered portfolio management with risk optimization. Smart rebalancing suggestions.",
    category: "portfolio",
    tags: ["AI", "Risk", "Rebalancing"],
    url: "https://aseto.com",
    pricing: "Free / $19/mo",
    rating: 3.8,
  },
  {
    id: "portfolio-manager",
    name: "Portfolio Manager by BraveNewCoin",
    description: "Institutional crypto portfolio management. Used by asset managers and funds.",
    category: "portfolio",
    tags: ["Institutional", "Asset Manager", "Funds"],
    url: "https://bravenewcoin.com/portfolio",
    pricing: "Enterprise",
    rating: 4.0,
  },
  {
    id: "copper",
    name: "Copper",
    description: "Institutional crypto custody and portfolio management. Secure storage with trading access.",
    category: "portfolio",
    tags: ["Institutional", "Custody", "Secure"],
    url: "https://copper.co",
    pricing: "Enterprise",
    rating: 4.2,
  },
  {
    id: "bitgo",
    name: "BitGo",
    description: "Institutional wallet and custody platform. Multi-signature security for institutions.",
    category: "portfolio",
    tags: ["Institutional", "Custody", "Multi-Sig"],
    url: "https://www.bitgo.com",
    pricing: "Enterprise",
    rating: 4.3,
  },
  {
    id: "fireblocks",
    name: "Fireblocks",
    description: "Institutional digital asset custody and transfer platform. Used by 1700+ institutions.",
    category: "portfolio",
    tags: ["Institutional", "Custody", "Transfer"],
    url: "https://www.fireblocks.com",
    pricing: "Enterprise",
    rating: 4.4,
  },
  {
    id: "anchorage",
    name: "Anchorage Digital",
    description: "Regulated crypto custody for institutions. FDIC-insured and SOC 2 certified.",
    category: "portfolio",
    tags: ["Institutional", "Regulated", "FDIC"],
    url: "https://www.anchorage.com",
    pricing: "Enterprise",
    rating: 4.2,
  },
  {
    id: "coinbase-custody",
    name: "Coinbase Custody",
    description: "Secure offline storage for institutional crypto assets. Regulated and insured.",
    category: "portfolio",
    tags: ["Institutional", "Offline", "Insured"],
    url: "https://www.coinbase.com/custody",
    pricing: "Enterprise",
    rating: 4.3,
  },
  // ========== DEFI AI (50 tools) ==========
  {
    id: "aixbt",
    name: "AIXBT",
    description: "Real-time crypto market intelligence AI agent on Virtuals protocol. Tracks 400+ KOLs and whale movements.",
    category: "defi",
    tags: ["AI Agent", "KOL Tracking", "Whales"],
    url: "https://aixbt.tech",
    pricing: "Token-based",
    rating: 4.4,
    featured: true,
  },
  {
    id: "derive",
    name: "Derive (ex-Lyra)",
    description: "Decentralized options and perpetuals with AI automation strategies. $1.5B+ cumulative volume.",
    category: "defi",
    tags: ["Options", "Perpetuals", "AI Strategy"],
    url: "https://derive.xyz",
    pricing: "Protocol Fees",
    rating: 4.3,
  },
  {
    id: "cod3x",
    name: "Cod3x",
    description: "AI agent for automated DeFi strategy execution across multiple protocols.",
    category: "defi",
    tags: ["AI Agent", "Automation", "Multi-Protocol"],
    url: "https://cod3x.org",
    pricing: "Token-based",
    rating: 4.0,
  },
  {
    id: "griffain",
    name: "Griffain",
    description: "AI-powered DeFi operations agent for complex yield strategies and portfolio optimization.",
    category: "defi",
    tags: ["AI Agent", "Yield", "Optimization"],
    url: "https://griffain.com",
    pricing: "Token-based",
    rating: 3.9,
  },
  {
    id: "hey-anon",
    name: "Hey Anon",
    description: "AI agent for DeFi automation with natural language commands. Execute complex DeFi ops with chat.",
    category: "defi",
    tags: ["AI Agent", "NLP", "Chat"],
    url: "https://heyanon.ai",
    pricing: "Token-based",
    rating: 4.1,
  },
  {
    id: "orbit-protocol",
    name: "Orbit Protocol",
    description: "Cross-chain DeFi AI tool for multi-chain yield optimization and bridging.",
    category: "defi",
    tags: ["Cross-Chain", "Yield", "Bridge"],
    url: "https://orbitprotocol.io",
    pricing: "Token-based",
    rating: 3.8,
  },
  {
    id: "neur",
    name: "Neur",
    description: "AI-driven DeFi analysis and strategy recommendation engine.",
    category: "defi",
    tags: ["AI Analysis", "Strategy", "Recommendation"],
    url: "https://neur.sh",
    pricing: "Token-based",
    rating: 3.9,
  },
  {
    id: "yieldforge",
    name: "YieldForge",
    description: "AI-powered DeFi yield optimization platform with risk-adjusted returns.",
    category: "defi",
    tags: ["Yield", "Optimization", "Risk"],
    url: "https://yieldforge.io",
    pricing: "Protocol Fees",
    rating: 4.0,
  },
  {
    id: "uniswap",
    name: "Uniswap",
    description: "Largest decentralized exchange by volume. AI-powered liquidity provision and routing.",
    category: "defi",
    tags: ["DEX", "Liquidity", "Routing"],
    url: "https://uniswap.org",
    pricing: "Protocol Fees",
    rating: 4.7,
  },
  {
    id: "curve",
    name: "Curve Finance",
    description: "Specialized AMM for stablecoins and pegged assets. Optimized for low-slippage trades.",
    category: "defi",
    tags: ["AMM", "Stablecoins", "Low Slippage"],
    url: "https://curve.fi",
    pricing: "Protocol Fees",
    rating: 4.5,
  },
  {
    id: "balancer",
    name: "Balancer",
    description: "Automated portfolio manager and trading platform. Multi-asset liquidity pools.",
    category: "defi",
    tags: ["AMM", "Portfolio", "Multi-Asset"],
    url: "https://balancer.fi",
    pricing: "Protocol Fees",
    rating: 4.3,
  },
  {
    id: "aave",
    name: "Aave",
    description: "Leading DeFi lending protocol. Flash loans, variable/stable rates, and safety module.",
    category: "defi",
    tags: ["Lending", "Flash Loan", "Safety Module"],
    url: "https://aave.com",
    pricing: "Protocol Fees",
    rating: 4.6,
  },
  {
    id: "compound",
    name: "Compound",
    description: "Decentralized lending protocol with cTokens. Earn interest on supplied assets.",
    category: "defi",
    tags: ["Lending", "cTokens", "Interest"],
    url: "https://compound.finance",
    pricing: "Protocol Fees",
    rating: 4.5,
  },
  {
    id: "maker",
    name: "MakerDAO",
    description: "Decentralized stablecoin protocol behind DAI. Vaults for collateralized borrowing.",
    category: "defi",
    tags: ["Stablecoin", "DAI", "Vaults"],
    url: "https://makerdao.com",
    pricing: "Protocol Fees",
    rating: 4.4,
  },
  {
    id: "lido",
    name: "Lido",
    description: "Liquid staking protocol for Ethereum and other PoS chains. Stake without locking.",
    category: "defi",
    tags: ["Liquid Staking", "Ethereum", "PoS"],
    url: "https://lido.fi",
    pricing: "Protocol Fees",
    rating: 4.5,
  },
  {
    id: "rocket-pool",
    name: "Rocket Pool",
    description: "Decentralized Ethereum staking pool. Trustless staking with rETH token.",
    category: "defi",
    tags: ["Staking", "Ethereum", "Trustless"],
    url: "https://rocketpool.net",
    pricing: "Protocol Fees",
    rating: 4.4,
  },
  {
    id: "yearn",
    name: "Yearn Finance",
    description: "Yield aggregation protocol. Auto-optimizes yield farming across multiple DeFi protocols.",
    category: "defi",
    tags: ["Yield", "Aggregation", "Auto-Optimize"],
    url: "https://yearn.finance",
    pricing: "Protocol Fees",
    rating: 4.3,
  },
  {
    id: "convex",
    name: "Convex Finance",
    description: "Yield booster for Curve liquidity providers. Maximize CRV rewards and yield.",
    category: "defi",
    tags: ["Yield", "Curve", "CRV"],
    url: "https://www.convexfinance.com",
    pricing: "Protocol Fees",
    rating: 4.2,
  },
  {
    id: "sushi",
    name: "SushiSwap",
    description: "Multi-chain DEX and DeFi platform. AMM, lending (Kashi), and launchpad (MISO).",
    category: "defi",
    tags: ["DEX", "Multi-Chain", "Launchpad"],
    url: "https://sushi.com",
    pricing: "Protocol Fees",
    rating: 4.1,
  },
  {
    id: "pancakeswap",
    name: "PancakeSwap",
    description: "Largest DEX on BNB Chain. AMM with farms, pools, and prediction markets.",
    category: "defi",
    tags: ["DEX", "BNB Chain", "Farms"],
    url: "https://pancakeswap.finance",
    pricing: "Protocol Fees",
    rating: 4.3,
  },
  {
    id: "quickswap",
    name: "QuickSwap",
    description: "Leading DEX on Polygon. Fast and low-cost trades with diverse token pairs.",
    category: "defi",
    tags: ["DEX", "Polygon", "Low-Cost"],
    url: "https://quickswap.exchange",
    pricing: "Protocol Fees",
    rating: 4.2,
  },
  {
    id: "traderjoe",
    name: "Trader Joe",
    description: "Primary DEX on Avalanche. AMM with lending (Banker Joe) and launchpad.",
    category: "defi",
    tags: ["DEX", "Avalanche", "Lending"],
    url: "https://traderjoexyz",
    pricing: "Protocol Fees",
    rating: 4.1,
  },
  {
    id: "velodrome",
    name: "Velodrome",
    description: "Optimism's primary DEX. Vote-escorted liquidity incentives and low fees.",
    category: "defi",
    tags: ["DEX", "Optimism", "VELO"],
    url: "https://velodrome.finance",
    pricing: "Protocol Fees",
    rating: 4.0,
  },
  {
    id: "aerodrome",
    name: "Aerodrome",
    description: "Base L2's leading DEX.承接 Curve veToken model on Base network.",
    category: "defi",
    tags: ["DEX", "Base", "veToken"],
    url: "https://aerodrome.finance",
    pricing: "Protocol Fees",
    rating: 3.9,
  },
  {
    id: "beefy",
    name: "Beefy Finance",
    description: "Multi-chain yield optimizer. Auto-compounding vaults across 20+ DeFi protocols.",
    category: "defi",
    tags: ["Yield", "Auto-Compound", "Multi-Chain"],
    url: "https://beefy.com",
    pricing: "Protocol Fees",
    rating: 4.3,
  },
  {
    id: "autofarm",
    name: "AutoFarm",
    description: "Cross-chain yield aggregator with auto-compounding. Optimal yield with minimal fees.",
    category: "defi",
    tags: ["Yield", "Auto-Compound", "Cross-Chain"],
    url: "https://autofarm.network",
    pricing: "Protocol Fees",
    rating: 4.1,
  },
  {
    id: "pickle",
    name: "Pickle Finance",
    description: "Yield farming optimizer with pJar vaults. Auto-compounding strategies.",
    category: "defi",
    tags: ["Yield", "pJar", "Auto-Compound"],
    url: "https://pickle.finance",
    pricing: "Protocol Fees",
    rating: 3.8,
  },
  {
    id: "harvest-finance",
    name: "Harvest Finance",
    description: "Yield farming aggregator with auto-compounding. Community-governed protocol.",
    category: "defi",
    tags: ["Yield", "Aggregator", "Community"],
    url: "https://harvest.finance",
    pricing: "Protocol Fees",
    rating: 3.9,
  },
  {
    id: "cream-finance",
    name: "Cream Finance",
    description: "Lending protocol with cross-chain support. Part of Yearn ecosystem.",
    category: "defi",
    tags: ["Lending", "Cross-Chain", "Yearn"],
    url: "https://cream.finance",
    pricing: "Protocol Fees",
    rating: 3.7,
  },
  {
    id: "iron-bank",
    name: "Iron Bank",
    description: "Capital-efficient lending protocol by Yearn. White-listed partner borrowing.",
    category: "defi",
    tags: ["Lending", "Capital Efficient", "Yearn"],
    url: "https://ironbank.finance",
    pricing: "Protocol Fees",
    rating: 3.9,
  },
  {
    id: "truefi",
    name: "TrueFi",
    description: "Uncollateralized lending protocol. AI-based credit scoring for institutional borrowers.",
    category: "defi",
    tags: ["Lending", "Uncollateralized", "AI Credit"],
    url: "https://truefi.io",
    pricing: "Protocol Fees",
    rating: 3.8,
  },
  {
    id: "goldfinch",
    name: "Goldfinch",
    description: "Decentralized credit protocol for real-world lending. No crypto collateral required.",
    category: "defi",
    tags: ["Credit", "Real-World", "No Collateral"],
    url: "https://goldfinch.finance",
    pricing: "Protocol Fees",
    rating: 3.9,
  },
  {
    id: "maple-finance",
    name: "Maple Finance",
    description: "Institutional capital lending. Pooled lending with KYC'd borrowers.",
    category: "defi",
    tags: ["Institutional", "Lending", "KYC"],
    url: "https://maple.finance",
    pricing: "Protocol Fees",
    rating: 3.8,
  },
  {
    id: "inverse-finance",
    name: "Inverse Finance",
    description: "Yield and lending protocol with DOLA stablecoin. Automated yield strategies.",
    category: "defi",
    tags: ["Yield", "Lending", "DOLA"],
    url: "https://inverse.finance",
    pricing: "Protocol Fees",
    rating: 3.7,
  },
  {
    id: "morpho",
    name: "Morpho",
    description: "Peer-to-peer layer on lending pools. Better rates for borrowers and lenders.",
    category: "defi",
    tags: ["P2P", "Lending", "Better Rates"],
    url: "https://morpho.xyz",
    pricing: "Protocol Fees",
    rating: 4.2,
  },
  {
    id: "euler",
    name: "Euler Finance",
    description: "Permissionless lending protocol. Borrow and lend almost any ERC-20 token.",
    category: "defi",
    tags: ["Permissionless", "ERC-20", "Lending"],
    url: "https://www.euler.finance",
    pricing: "Protocol Fees",
    rating: 4.0,
  },
  {
    id: "bancor",
    name: "Bancor",
    description: "AMM with single-sided liquidity and impermanent loss protection. v3 upgraded.",
    category: "defi",
    tags: ["AMM", "Single-Sided", "IL Protection"],
    url: "https://bancor.network",
    pricing: "Protocol Fees",
    rating: 3.9,
  },
  {
    id: "synapse",
    name: "Synapse Protocol",
    description: "Cross-chain AMM and bridge. Swap assets across 20+ blockchains seamlessly.",
    category: "defi",
    tags: ["Cross-Chain", "Bridge", "AMM"],
    url: "https://synapseprotocol.com",
    pricing: "Protocol Fees",
    rating: 4.1,
  },
  {
    id: "stargate",
    name: "Stargate Finance",
    description: "Omnichain liquidity transfer protocol. Unified liquidity across multiple chains.",
    category: "defi",
    tags: ["Omnichain", "Bridge", "Unified Liquidity"],
    url: "https://stargate.finance",
    pricing: "Protocol Fees",
    rating: 4.2,
  },
  {
    id: "hop",
    name: "Hop Protocol",
    description: "Cross-chain bridge for Ethereum L2s. Fast and secure asset transfers.",
    category: "defi",
    tags: ["L2", "Bridge", "Fast"],
    url: "https://hop.exchange",
    pricing: "Protocol Fees",
    rating: 4.0,
  },
  {
    id: "across",
    name: "Across",
    description: "Cross-chain bridge with UMA optimistic oracle. Fast and capital-efficient bridging.",
    category: "defi",
    tags: ["Bridge", "Optimistic", "UMA"],
    url: "https://across.to",
    pricing: "Protocol Fees",
    rating: 4.1,
  },
  {
    id: "anyswap",
    name: "Anyswap (Multichain)",
    description: "Multi-chain router protocol. Bridge tokens across 50+ blockchains.",
    category: "defi",
    tags: ["Multi-Chain", "Router", "50+ Chains"],
    url: "https://multichain.org",
    pricing: "Protocol Fees",
    rating: 3.8,
  },
  {
    id: "1inch-defi",
    name: "1inch DeFi",
    description: "DEX aggregator finding best prices across 100+ liquidity sources. Pathfinder algorithm.",
    category: "defi",
    tags: ["Aggregator", "Best Price", "100+ Sources"],
    url: "https://1inch.io",
    pricing: "Protocol Fees",
    rating: 4.5,
  },
  {
    id: "paraswap",
    name: "ParaSwap",
    description: "DEX aggregator with gas-optimized routing. Best execution for DeFi trades.",
    category: "defi",
    tags: ["Aggregator", "Gas-Optimized", "Best Execution"],
    url: "https://paraswap.io",
    pricing: "Protocol Fees",
    rating: 4.2,
  },
  {
    id: "cow-protocol",
    name: "Cow Protocol",
    description: "DEX with batch auctions and MEV protection. Get better prices with CoW (Coincidence of Wants).",
    category: "defi",
    tags: ["MEV Protection", "Batch Auction", "CoW"],
    url: "https://cow.fi",
    pricing: "Protocol Fees",
    rating: 4.3,
  },
  {
    id: "matcha",
    name: "Matcha",
    description: "DEX aggregator by 0x. Simple interface with best price discovery across DEXs.",
    category: "defi",
    tags: ["Aggregator", "0x", "Simple"],
    url: "https://matcha.xyz",
    pricing: "Protocol Fees",
    rating: 4.4,
  },
  {
    id: "slingshot",
    name: "Slingshot",
    description: "Cross-chain DEX aggregator. Trade across chains in one interface with low fees.",
    category: "defi",
    tags: ["Cross-Chain", "Aggregator", "Low Fees"],
    url: "https://slingshot.finance",
    pricing: "Protocol Fees",
    rating: 3.9,
  },
  {
    id: "openocean",
    name: "OpenOcean",
    description: "Full aggregator for DeFi and CeFi. Find best prices across CEX and DEX.",
    category: "defi",
    tags: ["Aggregator", "DeFi+CeFi", "Best Price"],
    url: "https://openocean.finance",
    pricing: "Protocol Fees",
    rating: 4.0,
  },
  {
    id: "perp",
    name: "Perpetual Protocol",
    description: "Decentralized perpetual futures trading. Up to 10x leverage with vAMM design.",
    category: "defi",
    tags: ["Perpetuals", "Leverage", "vAMM"],
    url: "https://perp.com",
    pricing: "Protocol Fees",
    rating: 4.1,
  },
  {
    id: "dydx",
    name: "dYdX",
    description: "Decentralized perpetual and margin trading. Orderbook-based with cross-margin.",
    category: "defi",
    tags: ["Perpetuals", "Orderbook", "Margin"],
    url: "https://dydx.exchange",
    pricing: "Protocol Fees",
    rating: 4.4,
  },
  {
    id: "gmx",
    name: "GMX",
    description: "Decentralized perpetual exchange on Arbitrum and Avalanche. Up to 50x leverage.",
    category: "defi",
    tags: ["Perpetuals", "50x Leverage", "Arbitrum"],
    url: "https://gmx.io",
    pricing: "Protocol Fees",
    rating: 4.5,
  },
  {
    id: "kwenta",
    name: "Kwenta",
    description: "Decentralized perpetuals trading on Optimism. Synthetix-powered synthetic assets.",
    category: "defi",
    tags: ["Perpetuals", "Optimism", "Synthetix"],
    url: "https://kwenta.io",
    pricing: "Protocol Fees",
    rating: 4.0,
  },
  {
    id: "synthetix",
    name: "Synthetix",
    description: "Synthetic asset protocol. Trade synths that track real-world asset prices on-chain.",
    category: "defi",
    tags: ["Synthetic", "Real-World", "On-Chain"],
    url: "https://www.synthetix.io",
    pricing: "Protocol Fees",
    rating: 4.2,
  },
];
