// ========== NEWS & DATA FEEDS (40 tools) ==========
export const newsDataTools = [
  {
    id: "the-block",
    name: "The Block",
    description: "Institutional-grade crypto news and research. Deep analysis with data-driven journalism.",
    category: "news-data",
    tags: ["Institutional", "Research", "Data-Driven"],
    url: "https://www.theblock.co",
    pricing: "Free / $125-500+/yr",
    rating: 4.5,
    featured: true,
  },
  {
    id: "coindesk",
    name: "CoinDesk",
    description: "Leading crypto news publication since 2013. Market data, indices, and Consensus events.",
    category: "news-data",
    tags: ["Leading", "Since 2013", "Consensus"],
    url: "https://www.coindesk.com",
    pricing: "Free / $149+/yr",
    rating: 4.4,
  },
  {
    id: "cointelegraph",
    name: "Cointelegraph",
    description: "Visual-heavy crypto journalism since 2013. News, reviews, and educational content.",
    category: "news-data",
    tags: ["Visual", "Since 2013", "Educational"],
    url: "https://cointelegraph.com",
    pricing: "Free",
    rating: 4.2,
  },
  {
    id: "decrypt",
    name: "Decrypt",
    description: "Award-winning crypto media with beginner-friendly explainers and deep dives.",
    category: "news-data",
    tags: ["Award-Winning", "Beginner-Friendly", "Explainers"],
    url: "https://decrypt.co",
    pricing: "Free / Premium",
    rating: 4.3,
  },
  {
    id: "bitcoin-magazine",
    name: "Bitcoin Magazine",
    description: "Oldest Bitcoin publication founded by Vitalik Buterin and Mihai Alisie in 2012.",
    category: "news-data",
    tags: ["Bitcoin", "Oldest", "Since 2012"],
    url: "https://bitcoinmagazine.com",
    pricing: "Free / $99/yr",
    rating: 4.4,
  },
  {
    id: "blockworks",
    name: "Blockworks",
    description: "Crypto news for institutional investors. Policy, markets, and DeFi coverage.",
    category: "news-data",
    tags: ["Institutional", "Policy", "DeFi"],
    url: "https://blockworks.co",
    pricing: "Free / Newsletter",
    rating: 4.1,
  },
  {
    id: "bankless",
    name: "Bankless",
    description: "Ethereum-focused media and education. Podcast, newsletter, and premium research.",
    category: "news-data",
    tags: ["Ethereum", "Podcast", "Premium Research"],
    url: "https://bankless.com",
    pricing: "Free / $15+/mo",
    rating: 4.4,
  },
  {
    id: "defi-pulse-news",
    name: "DeFi Pulse (News)",
    description: "DeFi news and educational content. Originally creators of DeFi Pulse Index.",
    category: "news-data",
    tags: ["DeFi", "Education", "Index"],
    url: "https://defipulse.com/blog",
    pricing: "Free",
    rating: 3.8,
  },
  {
    id: "the-defiant",
    name: "The Defiant",
    description: "DeFi-focused journalism and research. Daily newsletter with protocol deep dives.",
    category: "news-data",
    tags: ["DeFi", "Newsletter", "Deep Dives"],
    url: "https://thedefiant.io",
    pricing: "Free / $10+/mo",
    rating: 4.3,
  },
  {
    id: "protos",
    name: "Protos",
    description: "Crypto investigative journalism. Exposes fraud, hacks, and industry secrets.",
    category: "news-data",
    tags: ["Investigative", "Exposes", "Secrets"],
    url: "https://protos.com",
    pricing: "Free / Newsletter",
    rating: 4.0,
  },
  {
    id: "rekt-news",
    name: "Rekt News",
    description: "DeFi hack documentation and analysis. Learn from exploited protocols.",
    category: "news-data",
    tags: ["Hacks", "Analysis", "DeFi"],
    url: "https://rekt.news",
    pricing: "Free",
    rating: 4.2,
  },
  {
    id: "blockbeats",
    name: "BlockBeats",
    description: "Chinese crypto media outlet. Bilingual coverage of crypto news and projects.",
    category: "news-data",
    tags: ["Chinese", "Bilingual", "Projects"],
    url: "https://www.theblockbeats.info",
    pricing: "Free",
    rating: 4.1,
  },
  {
    id: "odaily",
    name: "Odaily",
    description: "Chinese blockchain news platform. Industry news, project reports, and market data.",
    category: "news-data",
    tags: ["Chinese", "Industry", "Reports"],
    url: "https://www.odaily.news",
    pricing: "Free",
    rating: 4.0,
  },
  {
    id: "foresight-news",
    name: "Foresight News",
    description: "Chinese crypto media with airdrop tracking and project research.",
    category: "news-data",
    tags: ["Chinese", "Airdrop", "Research"],
    url: "https://foresightnews.pro",
    pricing: "Free",
    rating: 3.9,
  },
  {
    id: "cryptopotato",
    name: "CryptoPotato",
    description: "Crypto news with price analysis and market updates. Beginner-friendly content.",
    category: "news-data",
    tags: ["Analysis", "Market", "Beginner"],
    url: "https://www.cryptopotato.com",
    pricing: "Free",
    rating: 4.0,
  },
  {
    id: "newsbtc",
    name: "NewsBTC",
    description: "Bitcoin and crypto news with technical analysis. Price predictions and guides.",
    category: "news-data",
    tags: ["Bitcoin", "TA", "Guides"],
    url: "https://www.newsbtc.com",
    pricing: "Free",
    rating: 3.9,
  },
  {
    id: "ambcrypto",
    name: "AMBCrypto",
    description: "Crypto news and analysis. Technology, regulation, and market coverage.",
    category: "news-data",
    tags: ["Technology", "Regulation", "Market"],
    url: "https://ambcrypto.com",
    pricing: "Free",
    rating: 3.8,
  },
  {
    id: "u-today",
    name: "U.Today",
    description: "Crypto and blockchain news with expert opinions. Price analysis and predictions.",
    category: "news-data",
    tags: ["Expert", "Price Analysis", "Predictions"],
    url: "https://u.today",
    pricing: "Free",
    rating: 3.7,
  },
  {
    id: "cointelegraph-research",
    name: "Cointelegraph Research",
    description: "Institutional-grade research reports by Cointelegraph. Quarterly and thematic reports.",
    category: "news-data",
    tags: ["Research", "Institutional", "Reports"],
    url: "https://research.cointelegraph.com",
    pricing: "Premium",
    rating: 4.3,
  },
  {
    id: "messari-research",
    name: "Messari Research",
    description: "Comprehensive crypto research platform. Protocol reports, sector analysis, and governance.",
    category: "news-data",
    tags: ["Protocol Reports", "Sector Analysis", "Governance"],
    url: "https://messari.io/research",
    pricing: "$29-1000+/mo",
    rating: 4.5,
  },
  {
    id: "delphi-digital",
    name: "Delphi Digital",
    description: "Premium crypto research firm. Deep protocol analysis and investment thesis.",
    category: "news-data",
    tags: ["Premium", "Protocol Analysis", "Investment"],
    url: "https://delphidigital.io",
    pricing: "Enterprise",
    rating: 4.6,
  },
  {
    id: "glassnode-research",
    name: "Glassnode Research",
    description: "On-chain research and insights. Weekly insights and institutional-grade reports.",
    category: "news-data",
    tags: ["On-Chain", "Weekly", "Institutional"],
    url: "https://insights.glassnode.com",
    pricing: "Premium",
    rating: 4.5,
  },
  {
    id: "chainalysis-blog",
    name: "Chainalysis Blog",
    description: "Blockchain analysis insights and reports. Compliance, crime, and market analysis.",
    category: "news-data",
    tags: ["Analysis", "Compliance", "Crime"],
    url: "https://blog.chainalysis.com",
    pricing: "Free",
    rating: 4.2,
  },
  {
    id: "a16z-crypto",
    name: "a16z Crypto",
    description: "Andreessen Horowitz crypto research. Industry thought leadership and regulatory insights.",
    category: "news-data",
    tags: ["VC", "Thought Leadership", "Regulation"],
    url: "https://a16z.com/crypto",
    pricing: "Free",
    rating: 4.4,
  },
  {
    id: "paradigm-research",
    name: "Paradigm Research",
    description: "Crypto-focused investment firm research. Trading strategies and market structure.",
    category: "news-data",
    tags: ["VC", "Trading", "Market Structure"],
    url: "https://www.paradigm.xyz/writing",
    pricing: "Free",
    rating: 4.3,
  },
  {
    id: "galaxy-research",
    name: "Galaxy Digital Research",
    description: "Institutional crypto research. Monthly reports, market overviews, and sector deep dives.",
    category: "news-data",
    tags: ["Institutional", "Monthly", "Sector"],
    url: "https://galaxy.com/research",
    pricing: "Free / Institutional",
    rating: 4.2,
  },
  {
    id: "coinmetrics",
    name: "Coin Metrics",
    description: "Crypto data and research for institutions. Network data, market data, and indices.",
    category: "news-data",
    tags: ["Data", "Institutional", "Indices"],
    url: "https://coinmetrics.io",
    pricing: "Enterprise",
    rating: 4.4,
  },
  {
    id: "amber-group-research",
    name: "Amber Group Research",
    description: "Crypto research by Amber Group. Trading insights and market analysis.",
    category: "news-data",
    tags: ["Trading", "Market Analysis", "Insights"],
    url: "https://ambergroup.io/research",
    pricing: "Free / Institutional",
    rating: 4.0,
  },
  {
    id: "kraken-intelligence",
    name: "Kraken Intelligence",
    description: "Research arm of Kraken exchange. Monthly market reports and deep analyses.",
    category: "news-data",
    tags: ["Monthly", "Deep Analysis", "Kraken"],
    url: "https://kraken.com/learn/intelligence",
    pricing: "Free",
    rating: 4.1,
  },
  {
    id: "binance-research",
    name: "Binance Research",
    description: "Binance's research division. Project reports, market analysis, and industry trends.",
    category: "news-data",
    tags: ["Project Reports", "Industry", "Trends"],
    url: "https://research.binance.com",
    pricing: "Free",
    rating: 4.0,
  },
  {
    id: "coingecko-research",
    name: "CoinGecko Research",
    description: "Crypto market reports by CoinGecko. Quarterly reports and industry analysis.",
    category: "news-data",
    tags: ["Quarterly", "Industry", "Analysis"],
    url: "https://www.coingecko.com/research",
    pricing: "Free / Premium",
    rating: 4.2,
  },
  {
    id: "cryptoslate",
    name: "CryptoSlate",
    description: "Crypto news and research with database of 3,000+ projects. Lists and reviews.",
    category: "news-data",
    tags: ["News", "Database", "3,000+ Projects"],
    url: "https://cryptoslate.com",
    pricing: "Free / Premium",
    rating: 4.1,
  },
  {
    id: "coinjournal",
    name: "CoinJournal",
    description: "Independent crypto news and analysis. Focus on technology and adoption.",
    category: "news-data",
    tags: ["Independent", "Technology", "Adoption"],
    url: "https://coinjournal.net",
    pricing: "Free",
    rating: 4.0,
  },
  {
    id: "beincrypto",
    name: "BeInCrypto",
    description: "Crypto education and news. Beginner guides, reviews, and market analysis.",
    category: "news-data",
    tags: ["Education", "Guides", "Reviews"],
    url: "https://beincrypto.com",
    pricing: "Free",
    rating: 4.1,
  },
  {
    id: "bitcoinist",
    name: "Bitcoinist",
    description: "Bitcoin-focused news and analysis. Price news, regulations, and adoption stories.",
    category: "news-data",
    tags: ["Bitcoin", "Regulation", "Adoption"],
    url: "https://bitcoinist.com",
    pricing: "Free",
    rating: 3.9,
  },
  {
    id: "crypto-briefing",
    name: "Crypto Briefing",
    description: "Independent crypto research and news. Project analysis and market insights.",
    category: "news-data",
    tags: ["Independent", "Project Analysis", "Insights"],
    url: "https://cryptobriefing.com",
    pricing: "Free / Premium",
    rating: 4.0,
  },
  {
    id: "tokenpost",
    name: "TokenPost",
    description: "Korean blockchain news platform. Global crypto news with Korean perspective.",
    category: "news-data",
    tags: ["Korean", "Global", "Blockchain"],
    url: "https://tokenpost.kr",
    pricing: "Free",
    rating: 3.8,
  },
  {
    id: "blockchain-news",
    name: "Blockchain News",
    description: "Blockchain technology news and use cases. Enterprise and government adoption coverage.",
    category: "news-data",
    tags: ["Technology", "Enterprise", "Government"],
    url: "https://blockchain.news",
    pricing: "Free",
    rating: 3.7,
  },
];
