// ========== CHART & TA (40 tools) ==========
export const chartTools = [
  {
    id: "tradingview",
    name: "TradingView",
    description: "The most widely used charting platform with community AI/ML indicators and custom Pine Script.",
    category: "charting",
    tags: ["Charts", "Pine Script", "Community"],
    url: "https://tradingview.com",
    affiliateUrl: "https://tradingview.com/partner-program",
    pricing: "Free / $14.95-59.95/mo",
    rating: 4.8,
    featured: true,
  },
  {
    id: "trendspider",
    name: "TrendSpider",
    description: "Automated pattern recognition with trendlines and key levels. AI reduces subjective bias in TA.",
    category: "charting",
    tags: ["Pattern Recognition", "Trendlines", "Automation"],
    url: "https://trendspider.com",
    affiliateUrl: "https://trendspider.com/?ref=affiliate",
    pricing: "$39-179/mo",
    rating: 4.4,
  },
  {
    id: "tickeron",
    name: "Tickeron",
    description: "AI pattern recognition and predictions across crypto, stocks, and ETFs. Machine learning TA.",
    category: "charting",
    tags: ["AI Prediction", "Pattern", "ML"],
    url: "https://tickeron.com",
    affiliateUrl: "https://tickeron.com/?ref=affiliate",
    pricing: "$25-250/mo",
    rating: 4.1,
  },
  {
    id: "coinglass",
    name: "CoinGlass",
    description: "Futures and options market data with liquidation heatmaps. Essential for derivatives traders.",
    category: "charting",
    tags: ["Futures", "Liquidation", "Heatmap"],
    url: "https://coinglass.com",
    affiliateUrl: "https://coinglass.com/account/affiliate",
    pricing: "Free / Premium",
    rating: 4.5,
  },
  {
    id: "coindance",
    name: "CoinDance",
    description: "Global Bitcoin nodes, volume, and blockchain stats. Simple visual charts.",
    category: "charting",
    tags: ["Bitcoin", "Nodes", "Visual"],
    url: "https://coindance.com",
    pricing: "Free",
    rating: 4.3,
  },
  {
    id: "painting-crypto",
    name: "Painting Crypto",
    description: "Automated chart pattern detection. Find heads & shoulders, triangles, and more.",
    category: "charting",
    tags: ["Pattern Detection", "Automated", "Chart"],
    url: "https://paintingcrypto.com",
    pricing: "$29-99/mo",
    rating: 3.9,
  },
  {
    id: "alphractal",
    name: "Alphractal",
    description: "AI-driven fractal analysis for crypto markets. Advanced pattern recognition.",
    category: "charting",
    tags: ["Fractal", "AI", "Advanced"],
    url: "https://alphractal.com",
    pricing: "Free / Premium",
    rating: 3.8,
  },
  {
    id: "crypto-quant",
    name: "CryptoQuant (Charts)",
    description: "On-chain charts with technical overlay. Combine on-chain and TA in one view.",
    category: "charting",
    tags: ["On-Chain", "TA", "Combined"],
    url: "https://cryptoquant.com",
    pricing: "$29-299/mo",
    rating: 4.4,
  },
  {
    id: "glassnode-charts",
    name: "Glassnode Charts",
    description: "On-chain charts with technical indicators. Premium data visualization.",
    category: "charting",
    tags: ["On-Chain", "TA", "Visualization"],
    url: "https://glassnode.com/studio",
    pricing: "$29-799/mo",
    rating: 4.5,
  },
  {
    id: "tradinglite",
    name: "TradingLite",
    description: "Lightweight TradingView alternative. Fast, simple, and affordable charting.",
    category: "charting",
    tags: ["Lightweight", "Alternative", "Affordable"],
    url: "https://tradinglite.com",
    pricing: "Free / $9.99/mo",
    rating: 4.0,
  },
  {
    id: "kagi-charts",
    name: "Kagi Charts",
    description: "Japanese charting technique implementation. Noise-free price movement visualization.",
    category: "charting",
    tags: ["Japanese", "Noise-Free", "Visualization"],
    url: "https://kagicharts.com",
    pricing: "Free / Premium",
    rating: 3.7,
  },
  {
    id: "multicharts",
    name: "MultiCharts",
    description: "Professional trading platform with AI optimization. For serious technical analysts.",
    category: "charting",
    tags: ["Professional", "AI Optimization", "Serious"],
    url: "https://multicharts.com",
    pricing: "$99-199/mo",
    rating: 4.2,
  },
  {
    id: "ninjatrader",
    name: "NinjaTrader (Crypto)",
    description: "Professional futures and crypto charting. Advanced order execution.",
    category: "charting",
    tags: ["Professional", "Futures", "Advanced"],
    url: "https://ninjatrader.com",
    pricing: "Free / $50-105/mo",
    rating: 4.3,
  },
  {
    id: "motivel-wave",
    name: "Motivel Wave",
    description: "Elliott Wave pattern recognition AI. Automated wave counting and prediction.",
    category: "charting",
    tags: ["Elliott Wave", "AI", "Automated"],
    url: "https://motivelwave.com",
    pricing: "$49-149/mo",
    rating: 3.9,
  },
  {
    id: "prophet-charts",
    name: "Prophet Charts",
    description: "AI-powered price prediction charts. Machine learning for crypto and stocks.",
    category: "charting",
    tags: ["AI", "Prediction", "ML"],
    url: "https://prophetecharts.com",
    pricing: "$29-99/mo",
    rating: 3.8,
  },
  {
    id: "cryptowatch",
    name: "CryptoWatch (Kraken)",
    description: "Clean, fast charting by Kraken. Professional-grade charts for crypto.",
    category: "charting",
    tags: ["Clean", "Fast", "Professional"],
    url: "https://cryptowat.ch",
    pricing: "Free / $9.99+/mo",
    rating: 4.4,
  },
  {
    id: "geckoterminal",
    name: "GeckoTerminal",
    description: "CoinGecko's charting terminal. DEX charts and on-chain data.",
    category: "charting",
    tags: ["DEX", "On-Chain", "Terminal"],
    url: "https://www.geckoterminal.com",
    pricing: "Free / $32.5+/mo",
    rating: 4.3,
  },
  {
    id: "birdeye",
    name: "Birdeye",
    description: "Solana DEX charting with real-time data. Fast and accurate charts.",
    category: "charting",
    tags: ["Solana", "DEX", "Real-time"],
    url: "https://birdeye.so",
    pricing: "Free / Premium",
    rating: 4.2,
  },
  {
    id: "dexscreener",
    name: "DEXScreener",
    description: "Real-time DEX pair charts across 50+ chains. Fast and free.",
    category: "charting",
    tags: ["DEX", "Real-time", "50+ Chains"],
    url: "https://dexscreener.com",
    pricing: "Free / API",
    rating: 4.5,
  },
  {
    id: "bubblemaps-chart",
    name: "Bubblemaps (Charts)",
    description: "Visual on-chain charting. See token distribution and wallet clusters.",
    category: "charting",
    tags: ["Visual", "On-Chain", "Clusters"],
    url: "https://bubblemaps.io/chart",
    pricing: "Free / Premium",
    rating: 4.1,
  },
  {
    id: "tokenterminal-chart",
    name: "Token Terminal (Charts)",
    description: "Financial charts for crypto protocols. Revenue, earnings, and valuation.",
    category: "charting",
    tags: ["Financial", "Revenue", "Valuation"],
    url: "https://tokenterminal.com",
    pricing: "Free / $99+/mo",
    rating: 4.3,
  },
  {
    id: "defillama-chart",
    name: "DeFi Llama (Charts)",
    description: "TVL charts for all DeFi protocols. Open-source and community-maintained.",
    category: "charting",
    tags: ["TVL", "DeFi", "Open-Source"],
    url: "https://defillama.com/chains",
    pricing: "Free",
    rating: 4.8,
  },
  {
    id: "messari-charts",
    name: "Messari (Charts)",
    description: "Institutional-grade crypto charts and research. High-quality data visualization.",
    category: "charting",
    tags: ["Institutional", "Research", "High-Quality"],
    url: "https://messari.io/charts",
    pricing: "$29-1000+/mo",
    rating: 4.5,
  },
  {
    id: "coingecko-charts",
    name: "CoinGecko (Charts)",
    description: "Largest crypto price charts. Free and premium data feeds.",
    category: "charting",
    tags: ["Price", "Free", "Premium"],
    url: "https://www.coingecko.com/en/coins/bitcoin",
    pricing: "Free / $32.5+/mo",
    rating: 4.7,
  },
  {
    id: "coinmarketcap-charts",
    name: "CoinMarketCap (Charts)",
    description: "Most referenced crypto price charts. Historical data and community ratings.",
    category: "charting",
    tags: ["Price", "Historical", "Community"],
    url: "https://coinmarketcap.com/currencies/bitcoin/",
    pricing: "Free / $19.99+/mo",
    rating: 4.6,
  },
  {
    id: "cryptocompare-charts",
    name: "CryptoCompare (Charts)",
    description: "Institutional-grade charting data. API used by financial institutions.",
    category: "charting",
    tags: ["Institutional", "API", "Financial"],
    url: "https://www.cryptocompare.com",
    pricing: "Free / Enterprise",
    rating: 4.3,
  },
  {
    id: "kaiko-charts",
    name: "Kaiko (Charts)",
    description: "Institutional crypto market data charts. Historical and real-time.",
    category: "charting",
    tags: ["Institutional", "Historical", "Real-time"],
    url: "https://www.kaiko.com",
    pricing: "Enterprise",
    rating: 4.4,
  },
  {
    id: "coinalyze-charts",
    name: "CoinAlyze (Charts)",
    description: "Futures trading charts with long/short ratios and funding rates.",
    category: "charting",
    tags: ["Futures", "Long/Short", "Funding"],
    url: "https://coinalyze.net",
    pricing: "Free / $29+/mo",
    rating: 4.4,
  },
  {
    id: "skew-charts",
    name: "Skew (Charts)",
    description: "Crypto derivatives charts now part of Coinbase. Professional-grade.",
    category: "charting",
    tags: ["Derivatives", "Professional", "Coinbase"],
    url: "https://www.skew.com",
    pricing: "Enterprise",
    rating: 4.3,
  },
  {
    id: "bybt-charts",
    name: "Bybt (Charts)",
    description: "Comprehensive futures and options charts. Liquidation maps.",
    category: "charting",
    tags: ["Futures", "Options", "Liquidation"],
    url: "https://bybt.com",
    pricing: "Free / Premium",
    rating: 4.5,
  },
  {
    id: "whale-alert-charts",
    name: "Whale Alert (Charts)",
    description: "Real-time large transaction charts. Know when whales move.",
    category: "charting",
    tags: ["Whales", "Real-time", "Large Tx"],
    url: "https://whale-alert.io/charts",
    pricing: "Free / $9.99+/mo",
    rating: 4.2,
  },
  {
    id: "whalemap-charts",
    name: "WhaleMap (Charts)",
    description: "Bitcoin whale wallet charting with heatmaps. Visual representation.",
    category: "charting",
    tags: ["Bitcoin", "Whales", "Heatmap"],
    url: "https://whalemap.com/charts",
    pricing: "Free / $19/mo",
    rating: 4.1,
  },
  {
    id: "checkonchain-charts",
    name: "Check On-Chain (Charts)",
    description: "Simple on-chain charts. Focus on Bitcoin and Ethereum key indicators.",
    category: "charting",
    tags: ["Bitcoin", "Ethereum", "Simple"],
    url: "https://checkonchain.com/charts",
    pricing: "Free",
    rating: 3.9,
  },
  {
    id: "lookintobitcoin-charts",
    name: "Look Into Bitcoin (Charts)",
    description: "Bitcoin on-chain charts with beautiful visualizations. HODL waves.",
    category: "charting",
    tags: ["Bitcoin", "Beautiful", "HODL"],
    url: "https://lookintobitcoin.com/charts",
    pricing: "Free / $19/mo",
    rating: 4.3,
  },
  {
    id: "woocharts-charts",
    name: "WooCharts",
    description: "Advanced on-chain charts with customizable indicators. Professional-grade.",
    category: "charting",
    tags: ["Advanced", "Customizable", "Professional"],
    url: "https://woocharts.com",
    pricing: "Free / $29/mo",
    rating: 4.1,
  },
];
